version: 2

models:
- name: rpt_xmau_metric_monthly
  description: '{{ doc("rpt_xmau_metric_monthly") }}'
  columns:
    - name: rpt_xmau_metric_monthly_id
      description: the unique ID of a monthly xMAU metric in rpt_xmau_metric_monthly
      tests:
        - not_null
        - unique
    - name: reporting_month
      description: Month in which the product usage was reported. This model only looks at the last 28 days of the month.
    - name: is_smau
      description: Denotes whether the event is identified as the stage's SMAU (stage monthly active user) metric. See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/) for metric definitions
    - name: is_gmau
      description: Denotes whether the event is identified as the stage's GMAU (group monthly active user) metric. See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/) for metric definitions
    - name: is_umau
      description: Denotes whether the event is identified as the stage's UMAU (unique monthly active user) metric. See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/) for metric definitions
    - name: stage_name
      description: The name of the product stage (Stages are aligned logically starting with the 7 loop stages of Plan, Create, Verify, Package, Release, Configure, and Monitor. We then add the value stages that we talk about in marketing, these include Manage, Secure, and Protect. Lastly, we add the team stages, Ecosystem, Growth, and Enablement. These stages have groups that rally around the same users, GitLab integrators, GitLab itself, and GitLab administrators respectively.).
    - name: section_name
      description: The name of the section (Sections are a collection of stages. We attempt to align these logically along common workflows like Dev, Sec and Ops.).
    - name: group_name
      description: The name of the group (A stage has one or more groups.).
    - name: user_group
    - name: event_name_array
    - name: event_count
      description: The count of events
    - name: namespace_count
      description: The count of namespaces
    - name: user_count
      description: The count of users
    - name: created_by
      description: Who created this model?
    - name: update_by
      description: Who updated this model last?
    - name: model_created_date
      description: The date at which the model was created
    - name: model_updated_date
      description: The date at which the model code was last updated
      
- name: rpt_usage_event_plan_monthly
  description: '{{ doc("rpt_usage_event_plan_monthly") }}'
  columns:
    - name: rpt_usage_event_plan_monthly_id
      description: the unique ID of a montthly usage event plan in rpt_usage_event_plan_monthly
      tests:
        - not_null
        - unique
    - name: reporting_month
      description: Month in which the product usage was reported. (this model only looks at the last 28 days of the month.)
    - name: plan_id_at_event_date
      description: The id of the plan on the day the event was created.
    - name: event_name
      description: The name tied to an event
    - name: stage_name
      description: The name of the product stage (Stages are aligned logically starting with the 7 loop stages of Plan, Create, Verify, Package, Release, Configure, and Monitor. We then add the value stages that we talk about in marketing, these include Manage, Secure, and Protect. Lastly, we add the team stages, Ecosystem, Growth, and Enablement. These stages have groups that rally around the same users, GitLab integrators, GitLab itself, and GitLab administrators respectively.).
    - name: section_name
      description: The name of the section (Sections are a collection of stages. We attempt to align these logically along common workflows like Dev, Sec and Ops.).
    - name: group_name
      description: The name of the group (A stage has one or more groups.).
    - name: is_smau
      description: Denotes whether the event is identified as the stage's SMAU (stage monthly active user) metric. See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
    - name: is_gmau
      description: Denotes whether the event is identified as the group's GMAU (group monthly active user) metric. See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
    - name: is_umau
      description: Denotes whether the event is identified as the UMAU (unique monthly active user) metric. See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
    - name: event_count
      description: The count of events
    - name: namespace_count
      description: The count of namespaces
    - name: user_count
      description: The count of users
    - name: created_by
      description: Who created this model?
    - name: update_by
      description: Who updated this model last?
    - name: model_created_date
      description: The date at which the model was created
    - name: model_updated_date
      description: The date at which the model code was last updated