Required:
  - PG_ADDRESS
  - PG_PORT
  - PG_DATABASE
  - PG_USERNAME
  - PG_PASSWORD

  - NETSUITE_HOST
  - NETSUITE_ENDPOINT
  - NETSUITE_EMAIL
  - NETSUITE_PASSWORD
  - NETSUITE_ROLE
  - NETSUITE_ACCOUNT
  - NETSUITE_APPID
  - NETSUITE_EARLIEST_DATE
