version: 2

models:
  - name: engineering_advisory_data
    description: '{{ doc("engineering_advisory_data") }}' 
    columns:
      - name: delta
      - name: filename
      - name: merge_date
      - name: package_type
      - name: publish_date
  - name: engineering_commit_stats
    description: This table details information about engineering commmit stats.
    columns:
      - name: commit_date
      - name: commit_id
  - name: engineering_nvd_data
    description: '{{ doc("engineering_nvd_data") }}'
    columns:
      - name: count
      - name: year
  - name: engineering_red_master_stats
    description: This table details data for when master has a red pipeline.
    columns:
      - name: backend_coverage
      - name: backend_coverage_absolute
      - name: backend_coverage_total
      - name: commit_date
      - name: jest_coverage
      - name: jest_coverage_absolute
      - name: jest_coverage_total
      - name: karma_coverage
      - name: karma_coverage_absolute
      - name: karma_coverage_total
  - name: engineering_part_of_product_merge_requests
    description: This table is a base table for merge request data for projects that are part of product.
    columns:
      - name: added_lines
      - name: real_size
      - name: removed_lines
      - name: plain_diff_url_path
        tests:
          - not_null
          - unique
  - name: engineering_handbook_merge_requests
    description: This table is a base table for merge request data for the handbook GitLab project.
    columns:
      - name: file_diffs
      - name: source_branch_name
      - name: merge_request_version_diffs
      - name: plain_diff_url_path
    
