version: 2

models:
    - name: monthly_recurring_revenue
      description: Base model for Zuora MRR
      columns:
          - name: account_number
            tests:
                - not_null
          - name: account_name
            tests:
                - not_null
          - name: product_category
            description: Product category is based on the rate plan name.
            tests:
              - accepted_values:
                      values: ['GitHost', 'Other', 'Gold', 'Basic', 'Bronze', 'Premium', 'Starter', 'Ultimate', 'Support', 'Plus', 'Silver', 'Standard', 'Trueup']
              - not_null          
          - name: rate_plan_charge_name
            tests:
                - not_null
    - name: non_gaap_revenue
      description: Base model for Zuora Non-GAAP Revenue
      columns:
          - name: account_number
            tests:
                - not_null
          - name: account_name
            tests:
                - not_null
          - name: rate_plan_charge_name
            tests:
                - not_null
          - name: product_category
            tests:
                - not_null
