version: 2

models:
  - name: license_db_add_ons
    description: This model is the data from tap-postgres for the add_ons table from license.gitlab.com. This data represents license add-ons such as support packages.
    columns:
      - name: add_on_id
        tests:
          - not_null
          - unique

  - name: license_db_granted_add_ons
    description: This model is the data from tap-postgres for the granted_add_ons table from license.gitlab.com. This data represents which add_ons are valid to which licenses.
    columns:
      - name: granted_add_on_id
        tests:
          - not_null
          - unique
      - name: license_id
        tests:
          - not_null
          - relationships:
              to: ref('license_db_licenses')
              field: license_id
      - name: add_on_id
        tests:
          - not_null
          - relationships:
              to: ref('license_db_add_ons')
              field: add_on_id

  - name: license_db_licenses
    description: This model is the data from tap-postgres for the licenses table from license.gitlab.com. This data represents the management of self-managed instances for GitLab customers.
    columns:
      - name: license_id
        tests:
          - not_null
          - unique

      - name: license_starts_at
        tests:
          - not_null
  