version: 2

sources:
  - name: twitter_keyhole
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: twitter_keyhole
    loader: Stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: overall_time
        description: '{{ doc("twitter_impressions") }}'
