name: 'gitlab_dw'
version: '1.0'

profile: 'gitlab'

source-paths: ["models"]

test-paths: ["tests"]

on-run-start:
    - '{{create_udfs()}}'

on-run-end:
    - grant usage on schema {{ target.schema }} to looker
    - grant select on all tables in schema {{ target.schema }} to looker
    - grant usage on schema {{ target.schema }}_meta to looker
    - grant select on all tables in schema {{ target.schema }}_meta to looker


models:
  logging:
    pre-hook: "{{ logging.log_model_start_event() }}"
    post-hook: "{{ logging.log_model_end_event() }}"

  gitlab_dw:
  # Models are materialized as views by default
    sfdc:
      transformed:
        enabled: true
        materialized: table

    netsuite:
      xf:
        enabled: true
        materialized: table

    pings:
      clean:
        enabled: true
        materialized: table

    pipe2spend:
      enabled: true
      materialized: table

    retention:
      enabled: true
      materialized: table

    zuora:
      xf:
        enabled: true
        materialized: table
