version: 2

sources:
  - name: zuora_api_sandbox
    tags: ["tdf","zuora_api_sandbox"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: zuora_api_sandbox_stitch
    loader: Stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: account
        columns:
          - name: id
            description: Primary Key for Accounts
            tests:
              - dbt_utils.expression_is_true:
                  expression: "id REGEXP '[0-9a-z]{32}'"
      - name: accounting_period
        identifier: accountingperiod
      - name: amendment
