connection_info:
  user: GITLAB_COM_DB_USER
  pass: GITLAB_COM_DB_PASS
  host: GITLAB_COM_DB_HOST
  database: GITLAB_COM_DB_NAME
  port: PG_PORT
tables:
  award_emoji:
    import_db: GITLAB_DB
    import_query: >
      SELECT id
      , name
      , user_id
      , awardable_id
      , awardable_type
      FROM award_emoji
      WHERE id = -1
    export_schema: 'gitlab_com'
    export_table: 'award_emoji'
    export_table_primary_key: id
