connection_info:
  user: GITLAB_COM_DB_USER
  pass: GITLAB_COM_DB_PASS
  host: GITLAB_COM_DB_HOST
  database: GITLAB_COM_DB_NAME
  port: PG_PORT
tables:
  namespaces:
      import_db: GITLAB_DB
      import_query: >
        SELECT id
        , name
        , path
        , owner_id
        , created_at
        , updated_at
        , type
        , avatar
        , membership_lock
        , share_with_group_lock
        , visibility_level
        , request_access_enabled
        , ldap_sync_status
        , ldap_sync_error
        , ldap_sync_last_update_at
        , ldap_sync_last_successful_update_at
        , ldap_sync_last_sync_at
        , lfs_enabled
        , parent_id
        , shared_runners_minutes_limit
        , repository_size_limit
        , require_two_factor_authentication
        , two_factor_grace_period
        , NULL AS plan_id
        , project_creation_level
        , auto_devops_enabled
        FROM namespaces
        WHERE updated_at BETWEEN '{EXECUTION_DATE}'::timestamp - interval '{HOURS} hours'
          AND '{EXECUTION_DATE}'::timestamp
      export_schema: 'gitlab_com'
      export_table: 'namespaces'
      export_table_primary_key: id