connection_info:
  database: GITLAB_COM_DB_NAME
  host: GITLAB_COM_DB_HOST
  pass: GITLAB_COM_DB_PASS
  port: GITLAB_COM_PG_PORT
  user: GITLAB_COM_DB_USER
tables:
  cluster_1:
    dbt_source_model: true
    export_schema: 'gitlab_dotcom'
    export_table: 'gitlab_pgp_export'
    export_table_primary_key: max_created_at
    import_db: GITLAB_DB
    import_query: |-
        SELECT 'gitlab_db_in_product_marketing_emails' AS table_name
        ,'created_at' as count_type
        , DATE(created_at) as date 
        , count(*) as number_of_records
        FROM in_product_marketing_emails
        WHERE DATE(created_at) > DATE(getdate())-8 
        UNION ALL
        SELECT 'gitlab_db_in_product_marketing_emails' AS table_name
        ,'created_at' as count_type
        , DATE(updated_at) as date
        , count(*) as number_of_records
        FROM in_product_marketing_emails
        WHERE DATE(updated_at) > DATE(getdate())-8 
        UNION ALL
        SELECT 'gitlab_db_clusters' AS table_name
        ,'created_at' as count_type
        , DATE(created_at) as date 
        , count(*) as number_of_records
        FROM clusters
        WHERE DATE(created_at) > DATE(getdate())-8 
        UNION ALL
        SELECT 'gitlab_db_clusters' AS table_name
        ,'created_at' as count_type
        , DATE(updated_at) as date
        , count(*) as number_of_records
        FROM clusters
        WHERE DATE(updated_at) > DATE(getdate())-8 



