version: 2

models:
    - name: zengrc_assessments
      description: '{{ doc("zengrc_assessments_desc") }}'
      columns: 
        - name: assessment_id
          tests:
            - not_null
            - unique

    - name: zengrc_audits
      description: '{{ doc("zengrc_audits_desc") }}'
      columns: 
        - name: audit_id
          tests:
            - not_null
            - unique

    - name: zengrc_controls
      description: '{{ doc("zengrc_controls_desc") }}'
      columns: 
        - name: control_id
          tests:
            - not_null
            - unique

    - name: zengrc_objectives
      description: '{{ doc("zengrc_objectives_desc") }}'
      columns: 
        - name: objective_id
          tests:
            - not_null
            - unique
    