# Globals defined at the bottom of the file

# Job Templates

.job_template: &job_definition
  image: registry.gitlab.com/gitlab-data/data-image/data-image:latest
  before_script:
    - export PATH="$CI_PROJECT_DIR/orchestration/:$PATH"
    - export PYTHONPATH="$CI_PROJECT_DIR/extract/:$CI_PROJECT_DIR/extract/shared_modules/:$PYTHONPATH"
    - if [ $SNOWFLAKE_DATABASE = "master" ]; then export SNOWFLAKE_LOAD_DATABASE="RAW"; else export SNOWFLAKE_LOAD_DATABASE="${CI_COMMIT_REF_NAME^^}_RAW"; fi
    - echo $SNOWFLAKE_LOAD_DATABASE
    - if [ $SNOWFLAKE_DATABASE = "master" ]; then export SNOWFLAKE_TRANSFORM_DATABASE="ANALYTICS"; else export SNOWFLAKE_TRANSFORM_DATABASE="${CI_COMMIT_REF_NAME^^}_ANALYTICS"; fi
    - echo $SNOWFLAKE_TRANSFORM_DATABASE
  tags:
    - analytics

# ---------------------------------------------------------------------------

# Stages
# Note some jobs come from global 'include' statements
stages:
  - review
  - setup
  - extract # extract/extract-ci.yml
  - model #  transform/snowflake-dbt/snowflake-dbt-ci.yml
  - model_tests #  transform/snowflake-dbt/snowflake-dbt-ci.yml
  - update
  - publish
  - review_stop

include:
  - "extract/extract-ci.yml"
  - "transform/snowflake-dbt/snowflake-dbt-ci.yml"

# Stage: review

# Set up a new instance in CloudSQL for testing in MRs
cloudsql_review: &cloudsql_review
  stage: review
  image: registry.gitlab.com/gitlab-data/data-image/data-image:latest
  variables:
    GIT_STRATEGY: clone
  tags:
    - analytics
  before_script:
    - export PATH="$CI_PROJECT_DIR/orchestration/:$PATH"
    - export PYTHONPATH="$CI_PROJECT_DIR/extract/:$CI_PROJECT_DIR/extract/shared_modules/:$PYTHONPATH"
  script:
    - ci_helpers.py manage_instances
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: review_stop
  only:
    - branches
  when: manual

# Force the re-creation of the CloudSQL instance for testing in MRs
cloudsql_review_refresh:
  <<: *cloudsql_review
  variables:
    FORCE: "true"
  when: manual

# Clone the ANALYTICS and RAW databases in Snowflake for use in MRs
snowflake_review: &snowflake_review
  stage: review
  image: registry.gitlab.com/gitlab-data/data-image/data-image:latest
  variables:
    GIT_STRATEGY: clone
  tags:
    - analytics
  before_script:
    - export PATH="$CI_PROJECT_DIR/orchestration/:$PATH"
    - export PYTHONPATH="$CI_PROJECT_DIR/extract/:$CI_PROJECT_DIR/extract/shared_modules/:$PYTHONPATH"
  script:
    - manage_snowflake.py manage_clones
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: review_stop
  only:
    refs:
      - branches
    variables:
      - $SNOWFLAKE_SYSADMIN_ROLE
      - $SNOWFLAKE_LOAD_WAREHOUSE
      - $SNOWFLAKE_LOAD_DATABASE       # make sure the guard works
      - $SNOWFLAKE_TRANSFORM_DATABASE  # make sure the guard works
  except:
    changes:
      - README.md
      - LICENSE
      - CODEOWNERS
      - .gitlab/*
    refs:
      - master
    variables:
      - $SNOWFLAKE_DATABASE == $SNOWFLAKE_LOAD_DATABASE
      - $SNOWFLAKE_DATABASE == $SNOWFLAKE_TRANSFORM_DATABASE
      - $TEST_PIPELINE
  when: manual

# Force re-clone the ANALYTICS and RAW databases in Snowflake for use in MRs
snowflake_review_refresh:
  <<: *snowflake_review
  script:
    - manage_snowflake.py manage_clones --force
  only:
    - branches
  when: manual

# Stage: setup

# Make sure that permissions are properly set in the CloudSQL instance for MRs
update_db: &update_db
  <<: *job_definition
  stage: setup
  script:
    - ci_helpers.py use_proxy "python3 orchestration/grant_roles.py"
  only:
    - branches
  when: manual

# Job template for applying pre-determined Snowflake permissions
.snowflake_permissions: &snowflake_permissions
  stage: setup
  <<: *job_definition
  image:
    name: registry.gitlab.com/meltano/meltano/runner:v0.3.0
    entrypoint: [""]
  script:
    - check_ci_cd_vars.py --file load/snowflake/required_ci_cd_vars.yaml
    - meltano permissions grant load/snowflake/snowflake_roles/config.yml --db snowflake $DRY

# Dry Run for applying the pre-determined Snowflake permissions
permission_bot_snowflake_dry:
  <<: *snowflake_permissions
  variables:
    DRY: "--dry"
    PERMISSION_BOT_USER: $SNOWFLAKE_PERMISSION_USER
    PERMISSION_BOT_PASSWORD: $SNOWFLAKE_PERMISSION_PASSWORD
    PERMISSION_BOT_ACCOUNT: $SNOWFLAKE_ACCOUNT
    PERMISSION_BOT_DATABASE: $SNOWFLAKE_PERMISSION_DATABASE
    PERMISSION_BOT_ROLE: $SNOWFLAKE_PERMISSION_ROLE
    PERMISSION_BOT_WAREHOUSE: $SNOWFLAKE_PERMISSION_WAREHOUSE
  only:
    refs:
      - master
    variables:
      - $PERMISSION_BOT_SNOWFLAKE

# Manual version of permission_bot_snowflake_dry
permission_bot_snowflake_dry_manual:
  <<: *snowflake_permissions
  variables:
    DRY: "--dry"
    PERMISSION_BOT_USER: $SNOWFLAKE_PERMISSION_USER
    PERMISSION_BOT_PASSWORD: $SNOWFLAKE_PERMISSION_PASSWORD
    PERMISSION_BOT_ACCOUNT: $SNOWFLAKE_ACCOUNT
    PERMISSION_BOT_DATABASE: $SNOWFLAKE_PERMISSION_DATABASE
    PERMISSION_BOT_ROLE: $SNOWFLAKE_PERMISSION_ROLE
    PERMISSION_BOT_WAREHOUSE: $SNOWFLAKE_PERMISSION_WAREHOUSE
  only:
    - branches
  except:
    - master
  when: manual

# Stage: update

# Takes data from dbt models, enriches it and uploads it back to SFDC.
# Also responsible for the tables in the sfdc_updates schema
sfdc_update: &sfdc_update
  stage: update
  <<: *job_definition
  script:
    - python3 transform/sfdc_processor.py upload_hosts
    - python3 transform/sfdc_processor.py generate_accounts
    - python3 transform/sfdc_processor.py update_accounts
  only:
    refs:
      - master
    variables:
      - $SFDC_UPDATE

# Manual version of sfdc_update
sfdc_update_manual:
  <<: *sfdc_update
  only:
    refs:
      - branches
  when: manual

# Semi-deprecated job that does a manual, full copy of the SFDC opportunity and account tables
sfdc_snapshot: &sfdc_snapshot
  stage: update
  <<: *job_definition
  script:
    - ci_helpers.py use_proxy "python3 extract/util/snapshot_opportunity.py"
    - ci_helpers.py use_proxy "python3 extract/util/snapshot_account.py"
  only:
    refs:
      - master
    variables:
      - $SFDC_SNAPSHOT

# Manual version of sfdc_snapshot
sfdc_snapshot_manual:
  stage: update
  <<: *sfdc_snapshot
  only:
    refs:
      - branches
  when: manual

# Stage: publish

# ======
# Pages
# ======

# Define some variables for use in other Pages jobs
.variables: &pages_job__variables
  SNOWFLAKE_ROLE: $SNOWFLAKE_TRANSFORM_ROLE
  SNOWFLAKE_WAREHOUSE: $SNOWFLAKE_TRANSFORM_WAREHOUSE

# Job template for use in the Pages publishing jobs
.pages_job_template: &pages_job_template
  stage: publish
  image: registry.gitlab.com/gitlab-data/data-image/data-image:latest
  variables: *pages_job__variables
  before_script:
    - export PATH="$CI_PROJECT_DIR/orchestration/:$PATH"
    - export PYTHONPATH="$CI_PROJECT_DIR/extract/:$CI_PROJECT_DIR/extract/shared_modules/:$PYTHONPATH"
  script:
    - generate_dbt_docs.sh
  artifacts:
    paths:
    - public
  tags:
    - analytics

# Run the script to generate the dbt docs and stand them up in gitlab pages
pages:
  <<: *pages_job_template
  variables:
    <<: *pages_job__variables
    SNOWFLAKE_DATABASE: $SNOWFLAKE_TRANSFORM_DATABASE
  only:
    refs:
      - master
    variables:
      - $DEPLOY_DBT_PAGES

# Manual, dry-run version of the pages job
test_dbt_pages:
  <<: *pages_job_template
  only:
    - branches
  except:
    - master
  when: manual


# Stage: review_stop

# Delete the Snowflake cloned database used for MRs
review_stop:
  stage: review_stop
  image: registry.gitlab.com/gitlab-data/data-image/data-image:latest
  variables:
    GIT_STRATEGY: none
  script:
    - git clone $CI_REPOSITORY_URL
    - analytics/orchestration/manage_snowflake.py delete_clone
  when: manual
  allow_failure: true
  only:
    refs:
      - branches
    variables:
      - $SNOWFLAKE_SYSADMIN_ROLE
      - $SNOWFLAKE_LOAD_WAREHOUSE
      - $SNOWFLAKE_LOAD_DATABASE       # make sure the guard works
      - $SNOWFLAKE_TRANSFORM_DATABASE  # make sure the guard works
  except:
    changes:
      - README.md
      - LICENSE
      - CODEOWNERS
    refs:
      - master
    variables:
      - $SNOWFLAKE_DATABASE == $SNOWFLAKE_LOAD_DATABASE
      - $SNOWFLAKE_DATABASE == $SNOWFLAKE_TRANSFORM_DATABASE
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - housekeeping

#--------------------------------------------------------------------------

# Global definitions

# Global variables
variables:
  PYTHONPATH: "$CI_PROJECT_DIR/extract/:$CI_PROJECT_DIR/extract/shared_modules/:$PYTHONPATH"
  SNOWFLAKE_DATABASE: "$CI_COMMIT_REF_NAME"

