stages:
  - build
  - extract

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

extract_container:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - analytics
  services:
    - docker:dind
  script:
    - docker build -t extract:$CI_COMMIT_REF_NAME containers/extract
    - docker push extract:$CI_COMMIT_REF_NAME

sfdc:
  stage: extract
  image: extract:$CI_COMMIT_REF_NAME
  tags:
    - analytics
  script:
    - envsubst < "/bizops/elt/config/kettle/kettle.repositories" > "$KETTLE_HOME/.kettle/kettle.properties"
    - cp "/bizops/elt/config/kettle/repositories.xml" "$KETTLE_HOME/.kettle/repositories.xml"
