resource_rules:
    issues:
      rules:
        - name: find all open issues - any label (simple - should be lots)
          conditions:
            state: opened
        - name: Issues needing triage
          conditions:
            state: opened
            forbidden_labels: 
              - Workflow
              - Triage
              - Needs Triage
            author_member:
              source: group
              condition: not_member_of
              source_id: 4347861
            assignee_member:
              source: group
              condition: not_member_of
              source_id: 4347861
              