version: '3.7'
services:
    webserver:
        image: registry.gitlab.com/gitlab-data/data-image/airflow-image:latest
        restart: always
        ports:
          - "8080:8080"
        env_file:
          - airflow.env
        environment:
          AIRFLOW__CORE__DAGS_FOLDER: /usr/local/airflow/analytics/dags/
          NAMESPACE: testing
        command: bash -c "airflow webserver"
        volumes:
          - type: volume
            source: airflow_logs
            target: /usr/local/airflow/logs
          - type: bind
            source: .
            target: /usr/local/airflow/analytics
            read_only: True
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        image: registry.gitlab.com/gitlab-data/data-image/airflow-image:latest
        restart: always
        ports:
          - "8793:8793"
        env_file:
          - airflow.env
        environment:
          AIRFLOW__CORE__DAGS_FOLDER: /usr/local/airflow/analytics/dags/
          NAMESPACE: testing
        command: bash -c "airflow scheduler"
        volumes:
          - type: volume
            source: airflow_logs
            target: /usr/local/airflow/logs
          - type: bind
            source: .
            target: /usr/local/airflow/analytics
            read_only: True
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
  airflow_logs:
