config:
    send_anonymous_usage_stats: False
    use_colors: True

gitlab-snowflake:
  target: prod
  outputs:
    prod:
      type: snowflake
      threads: 16
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_PREP_DATABASE') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_TRANSFORM_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_PREPARATION_SCHEMA') }}"
      client_session_keep_alive: True
    ci:
      type: snowflake
      threads: 16
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_PREP_DATABASE') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_TRANSFORM_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_PREPARATION_SCHEMA') }}"