config:
    send_anonymous_usage_stats: False
    use_colors: True

gitlab-snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 8
      account: gitlab
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: pluthra
      database: ANALYTICS
      warehouse: ANALYST_XS
      schema: "{{ env_var('SNOWFLAKE_TRANSFORM_SCHEMA') }}"
    docs:
      type: snowflake
      threads: 8
      account: gitlab
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: pluthra
      database: ANALYTICS
      warehouse: ANALYST_XS
      schema: ANALYTICS
