config:
    send_anonymous_usage_stats: False
    use_colors: True

gitlab-snowflake:
  outputs:
    prod:
      type: snowflake
      threads: 1
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      schema: "{{ env_var('SF_PROD_SCHEMA') }}"
  target: prod

