sfdc_sales_accepted_opportunity:
    constraints:
        not_null:
            - opportunity_segment
            - opportunity_name

users:
    constraints:
        unique:
            - id

sfdc_accounts_xf:
    constraints:
        not_null:
            - account_id
            - account_name
        unique:

sfdc_proof_of_concept_xf:
    constraints:
        not_null:
            - poc_id
            - account_id
            - opportunity_id
            - poc_status
        unique:
            - poc_id