name: 'gitlab_dw'
version: '1.0'

profile: 'gitlab'

source-paths: ["models"]

test-paths: ["tests"]

on-run-end:
    - grant usage on schema {{ target.schema }} to looker
    - grant select on all tables in schema {{ target.schema }} to looker

models:
  gitlab_dw:
    date:
      base:
        enabled: true
        materialized: view

    sfdc:
      base:
        enabled: true
        materialized: view
      transformed:
        enabled: true
        materialized: table

    pings:
      base:
        enabled: true
        materialized: view
        usage_data_unpacked:
          materialized: incremental
          sql_where: 'TRUE'
      clean:
        enabled: true
        materialized: table

    zuora:
      base:
        enabled: true
        materialized: table
