name: 'gitlab_dw'
version: '1.0'

profile: 'gitlab'

source-paths: ["models"]

models:
  gitlab_dw:
    sfdc:
      base:
        enabled: true
        materialized: view
      transformed:
        enabled: true
        materialized: table


on-run-end:
  - 'GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO metabase'