name: 'gitlab_dw'
version: '1.0'

profile: 'gitlab'

source-paths: ["models"]

models:
  gitlab_dw:
      base:
          enabled: true
          materialized: view
      transformed:
          enabled: true
          materialized: table
