version: 2

sources:
  - name: netsuite
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: netsuite_fivetran
    loader: fivetran
    loaded_at_field: _FIVETRAN_SYNCED

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: accounting_books
      - name: accounting_periods
      - name: accounts
      - name: budget
      - name: budget_category
      - name: classes
      - name: consolidated_exchange_rates
      - name: currencies
      - name: customers
      - name: departments
      - name: entity
        columns:
          - name: entity_name
            meta:
              sensitive: true
          - name: entity_full_name
            meta:
              sensitive: true
      - name: posting_account_activity
      - name: subsidiaries
        columns:
          - name: subsidiary_full_name
            meta:
              sensitive: true
          - name: subsidiary_name
            meta:
              sensitive: true
      - name: transaction_lines
        columns:
          - name: transaction_id
            tests:
              - relationships:
                  to: source('netsuite', 'transactions')
                  field: transaction_id
                  severity: warn
          - name: memo
            meta:
              sensitive: true
      - name: transactions
      - name: vendors
        columns:
          - name: vendor_name
            meta:
              sensitive: true
