version: 2

models:
- name: rpt_event_xmau_metric_monthly
  description: '{{ doc("rpt_event_xmau_metric_monthly") }}'
  columns:
    - name: xmau_metric_monthly_id
      description: the unique ID of a monthly xMAU metric in rpt_xmau_metric_monthly
      tests:
        - not_null
        - unique
    - name: event_calendar_month
      description: The first day of the calendar month of the event (ex. 2022-05-01, etc). This model only looks at the last 28 days of the month.
    - name: is_smau
      description: Boolean flag set to True if the event is chosen for the stage's SMAU metric
    - name: is_gmau
      description: Boolean flag set to True if the event is chosen for the group's GMAU metric
    - name: is_umau
      description: Boolean flag set to True if the event is chosen for the UMAU metric
    - name: stage_name
      description: The name of the product stage (ex. secure, plan, create, etc)
    - name: section_name
      description: The name of the product section (ex. dev, ops, etc)
    - name: group_name
      description: The name of the product group (ex. code_review, project_management, etc)
    - name: user_group
      description: Type of user based on the ultimate parent namespace's plan on the last event of the month (total, free, paid). Trial namespaces are considered to be free
    - name: event_name_array
      description: Array containing the event_names included in the xMAU metric
    - name: event_count
      description: The count of events generated
    - name: ultimate_parent_namespace_count
      description: The count of distinct ultimate parent namespaces in which an event was generated
    - name: user_count
      description: The count of distinct users who generated an event
    - name: created_by
      description: The GitLab handle of the original model creator
    - name: updated_by
      description: The GitLab handle of the most recent model editor
    - name: model_created_date
      description: Manually input ISO date of when model was original created
    - name: model_updated_date
      description: Manually input ISO date of when model was updated
    - name: dbt_updated_at
    - name: dbt_created_at

- name: rpt_event_plan_monthly
  description: '{{ doc("rpt_event_plan_monthly") }}'
  columns:
    - name: event_plan_monthly_id
      description: the unique ID of a montthly usage event plan in rpt_usage_event_plan_monthly
      tests:
        - not_null
        - unique
    - name: event_calendar_month
      description: The first day of the calendar month of the event (ex. 2022-05-01, etc). This model only looks at the last 28 days of the month.
    - name: event_calendar_quarter
      description: The calendar quarter of the event (ex. 2022-Q2, etc)
    - name: event_calendar_year
      description: The calendar year of the event (ex. 2022, etc)
    - name: plan_id_at_event_date
      description: The ID of the ultimate parent namespace's plan on the last event of the month (ex. 34, 100, 101, etc)
    - name: event_name
      description: The name tied to an event
    - name: is_smau
      description: Boolean flag set to True if the event is chosen for the stage's SMAU metric
    - name: is_gmau
      description: Boolean flag set to True if the event is chosen for the group's GMAU metric
    - name: is_umau
      description: Boolean flag set to True if the event is chosen for the UMAU metric
    - name: stage_name
      description: The name of the product stage (ex. secure, plan, create, etc)
    - name: section_name
      description: The name of the product section (ex. dev, ops, etc)
    - name: group_name
      description: The name of the product group (ex. code_review, project_management, etc)
    - name: event_count
      description: The count of events generated
    - name: ultimate_parent_namespace_count
      description: The count of distinct ultimate parent namespaces in which an event was generated
    - name: user_count
      description: The count of distinct users who generated an event
    - name: created_by
      description: The GitLab handle of the original model creator
    - name: updated_by
      description: The GitLab handle of the most recent model editor
    - name: model_created_date
      description: Manually input ISO date of when model was original created
    - name: model_updated_date
      description: Manually input ISO date of when model was updated
    - name: dbt_updated_at
    - name: dbt_created_at

- name: rpt_ping_metric_first_last_versions
  description: ' {{ doc("rpt_ping_metric_first_last_versions") }} '
  columns:
    - name: ping_metric_first_last_versions_id
      tests:
        - not_null
        - unique

- name: rpt_ping_latest_subscriptions_monthly
  description: ' {{ doc("rpt_ping_latest_subscriptions_monthly") }} '
  columns:
    - name: ping_latest_subscriptions_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_subscriptions_on_versions_estimate_factors_monthly
  description: ' {{ doc("rpt_ping_subscriptions_on_versions_estimate_factors_monthly") }} '
  columns:
    - name: ping_subscriptions_on_versions_estimate_factors_monthly_id
      tests:
        - not_null
        - unique
      description: the unique composite ID for the rpt_ping_instance_metric_adoption_monthly model consisting of reporting_month, metrics_path, and estimation_grain
    - name: ping_created_at_month
      description: The month when the ping was created
    - name: reporting_count
      description: The number of seats/subscriptions that reported on a version with the metric
    - name: not_reporting_count
      description: The number of seats/subscriptions that did not report on a version with the metric
    - name: total_count
      description: The total number of active seats/subscriptions that could have reported on a version with the metric
    - name: estimation_grain
      description: The estimation methodology being used, made up of a condition (ie. on a version with the metric) and a measure (ex. subscription count)
    - name: percent_reporting
      description: The percentage of seats/subscriptions on a version with the metric
    - name: stage_name
      description: The name of the product stage responsible for the metric
    - name: section_name
      description: The name of the product section responsible for the metric
    - name: group_name
      description: The name of the product group responsible for the metric
    - name: is_smau
      description: Boolean flag set to True if the metric is one of the counters chosen for the stage's SMAU calculation
    - name: is_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's GMAU calculation
    - name: is_paid_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's paid GMAU calculation
    - name: is_umau
      description: Boolean flag set to True if the metric is one of the counters chosen for UMAU calculation

- name: rpt_ping_metric_estimate_factors_monthly
  description: ' {{ doc("rpt_ping_metric_estimate_factors_monthly") }} '
  columns:
    - name: ping_metric_estimate_factors_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_subscriptions_reported_estimate_factors_monthly
  description: ' {{ doc("rpt_ping_subscriptions_reported_estimate_factors_monthly") }} '
  columns:
    - name: ping_subscriptions_reported_estimate_factors_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_metric_totals_w_estimates_monthly
  description: ' {{ doc("rpt_ping_metric_totals_w_estimates_monthly") }} '
  columns:
    - name: ping_metric_totals_w_estimates_monthly_id
      tests:
        - not_null
        - unique
      description: the unique composite ID for the rpt_ping_metric_totals_w_estimates_monthly model consisting of reporting_month, metrics_path, estimation_grain, ping_edition_product_tier, and service_ping_delivery_type
    - name: metrics_path
      description: The unique JSON key path of identifier of the metric in the ping payload. This appears as key_path in the metric definition YAML files
    - name: ping_created_at_month
      description: The month when the ping was created
    - name: ping_delivery_type
      description: How the product is delivered to the installation (Self-Managed, SaaS)
    - name: ping_edition
      description: The edition of GitLab on the installation (EE, CE)
    - name: ping_product_tier
      description: The product tier of the ping, inferred from the edition and the plan saved in the license (Core, Starter Premium, Ultimate)
    - name: ping_edition_product_tier
      description: A combination of the ping_edition and the ping_product_tier (EE - Self-Managed - Free, EE - Self-Managed - Premium, EE - Self-Managed - Ultimate)
    - name: stage_name
      description: The name of the product stage responsible for the metric
    - name: section_name
      description: The name of the product section responsible for the metric
    - name: group_name
      description: The name of the product group responsible for the metric
    - name: is_smau
      description: Boolean flag set to True if the metric is one of the counters chosen for the stage's SMAU calculation
    - name: is_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's GMAU calculation
    - name: is_paid_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's paid GMAU calculation
    - name: is_umau
      description: Boolean flag set to True if the metric is one of the counters chosen for UMAU calculation
    - name: reporting_count
      description: The number of seats/subscriptions that met the condition (ex. reported the metric)
    - name: not_reporting_count
      description: The number of seats/subscriptions that did not meet the condition (ex. report the metric)
    - name: percent_reporting
      description: The percentage of the measure (subscriptions or seats) meeting the condition (ex. reporting the metric)
    - name: estimation_grain
      description: The estimation methodology being used, made up of a condition (ex. reporting a metric) and a measure (ex. subscription count)
    - name: total_usage_with_estimate
      description: Total usage, including the estimate
    - name: estimated_usage
      description: Estimated usage based on recorded data and estimation grain/methodology
    - name: recorded_usage
      description: Actual recorded usage
    - name: created_by
      description: The GitLab handle of the original model creator
    - name: updated_by
      description: The GitLab handle of the most recent model editor
    - name: model_created_date
      description: Manually input ISO date of when model was original created
    - name: model_updated_date
      description: Manually input ISO date of when model was updated
    - name: dbt_updated_at
    - name: dbt_created_at


- name: rpt_ping_subscriptions_reported_counts_monthly
  description: ' {{ doc("rpt_ping_subscriptions_reported_counts_monthly") }} '
  columns:
    - name: ping_subscriptions_reported_counts_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_subscriptions_on_versions_counts_monthly
  description: ' {{ doc("rpt_ping_subscriptions_on_versions_counts_monthly") }} '
  columns:
    - name: ping_subscriptions_on_versions_counts_monthly_id
      tests:
        - not_null
        - unique
