version: 2

sources:
  - name: snowplow
    database: RAW
    schema: snowplow
    loader: copy_function # informational only (free text)
    loaded_at_field: uploaded_at # configure for all sources

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: events
        identifier: events
        columns:
          - name: json_text
            tests:
              - not_null
          - name: uploaded_at
            tests:
              - not_null
      - name: events_sample
        description: This is a 1 to 7 day sample of the main event data used for development and CI validation.
        identifier: events_sample
        columns:
          - name: json_text
            tests:
              - not_null
          - name: uploaded_at
            tests:
              - not_null

