version: 2

models:
    -   name: snowplow_unnested_events
        description: This is the primary events table. It unpacks all of the JSON, including these unstructured events - [link click tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#39-link-click-tracking), [form tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#3101-enableformtracking), and [time tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#timing).
        columns:
            -   name: uploaded_at
                tests:
                    - not_null