version: 2

models:
    - name: qualtrics_contact_mailing_send
      description: 'All mailings sent to individual Qualtrics contacts, as well as the time in which they were sent.'
      columns:
        - name: contact_email
          tests:
            - not_null
        - name: mailing_sent_at
          tests:
            - not_null
        - name: survey_name
          tests:
            - not_null
    - name: nps_answers
      description: 'Answers to various nps survey questions joined with various information about the user and their response.'
      columns:
        - name: distribution_channel
        - name: finished_survey
          tests:
            - not_null
        - name: question_description
        - name: question_id
            - not_null
        - name: question_response
        - name: response_id
        - name: response_recorded_at
          tests:
            - not_null
        - name: user_language