version: 2
models:
- name: sheetload_regional_quota_xf
  columns:
  - name: region_quota_id
    tests:
    - not_null
    - unique
- name: sheetload_sales_quota_xf
  columns:
  - name: sales_quota_id
    tests:
    - not_null
    - unique
