version: 2
models:
- name: engineering_pulse_survey
  description: This model aggregates the engineering pulse survey data into one table for reporting purposes.
  columns:
  - name: response_id
    tests:
    - not_null
    - unique
  - name: survey_id
    tests:
    - not_null
- name: sheetload_certificates_unioned
  columns:
  - name: date_completed
    tests:
    - not_null
  - name: submitter_name
    tests:
    - not_null
  - name: correct_responses
    tests:
    - not_null
  - name: total_responses
    tests:
    - not_null
  - name: is_team_member
    tests:
    - not_null
  - name: submitter_email
    tests:
    - not_null
  - name: certificate_name
    tests:
    - not_null
  - name: last_updated_at
    tests:
    - not_null
