version: 2

models:
  - name: prep_crm_account
    columns:
      - name: dim_crm_account_id
        description: account id from SFDC identifing the customer
      - name: crm_account_name
        description: account name from SFDC
      - name: crm_account_country
        description: billing country of SFDC account
      - name: dim_parent_crm_account_id
        description: ultimate parent account id
      - name: ultimate_parent_account_name
        description: parent account name
      - name: ultimate_parent_account_segment
        description: Sales segment of the parent account
      - name: ultimate_parent_billing_country
        description: billing country of parent account
      - name: record_type_id
      - name: federal_account
      - name: gitlab_com_user
      - name: is_jihu_account
      - name: account_owner
      - name: account_owner_team
      - name: account_type
      - name: gtm_strategy
      - name: technical_account_manager
      - name: is_deleted
        description: flag indicating if account has been deleted
      - name: is_reseller
        description: Identify whether a crm_account is a reseller.
      - name: merged_to_account_id
        description: for deleted accounts this is the SFDC account they were merged to
      - name: crm_account_created_date
        description: The date on which the CRM account was created in SFDC