version: 2

sources:
  - name: version
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_postgres
    loaded_at_field: _uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: usage_data
        identifier: version_db_usage_data
      - name: version_checks
        identifier: version_db_version_checks