version: 2

models:
    - name: dbt_source_status
      description: 'The current status of all DBT sources along with when the sources were last loaded.'
      columns:
        - name: freshness_observed_at
          tests:
            - not_null
        - name: latest_load_at
          tests:
            - not_null
        - name: source_freshness_state
          tests:
            - not_null
        - name: table_name
          tests:
            - not_null
            - unique
    - name: dbt_compilation_runtime
      description: 'The most recent not null compilation time elapsed for each DBT model.'
      columns:
        - name: model_name
          tests:
            - not_null
            - unique
        - name: compilation_time_seconds_elapsed
          tests:
            - not_null            
        