spec_profiling_results:
  import_db: CI_STATS_DB
  import_query: >
    SELECT id, commit, date, file, line_number, description, time as spec_time, 
           status, exception, query_count, query_time, request_count, request_time, 
           created_at, updated_at, branch
    FROM spec_profiling_results
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{hours} hour'
  export_db: EXPORT_DB
  export_schema: 'ci_stats'
  export_table: 'spec_profiling_results'
  export_table_schema:
    id: integer
    commit: character varying
    date: timestamp without time zone
    file: text
    line_number: integer
    description: text
    spec_time: numeric
    status: character varying
    exception: text
    query_count: integer
    query_time: numeric
    request_count: integer
    request_time: numeric
    branch: character varying
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
  export_table_primary_key: id
