customers:
  import_db: CUSTOMERS_DB
  import_query: >
    SELECT *
    FROM customers
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'customers'
  export_table: 'customers'
  export_table_schema:
    id: integer
    zuora_account_id: character varying
    salesforce_account_id: character varying
    billable: boolean
    sign_in_count: integer
    current_sign_in_at: timestamp without time zone
    last_sign_in_at: timestamp without time zone
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
  export_table_primary_key: id
orders:
  import_db: CUSTOMERS_DB
  import_query: >
    SELECT *
    FROM orders
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'customers'
  export_table: 'orders'
  export_table_schema:
    id: integer
    customer_id: integer
    product_rate_plan_id: character varying
    subscription_id: character varying
    subscription_name: character varying
    start_date: date
    end_date: date
    quantity: integer
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
  export_table_primary_key: id
versions:
  import_db: CUSTOMERS_DB
  import_query: >
    SELECT *
    FROM versions
    WHERE created_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'customers'
  export_table: 'versions'
  export_table_schema:
    id: integer
    item_type: character varying
    item_id: integer
    event: character varying
    transaction_id: integer
    created_at: timestamp without time zone
  export_table_primary_key: id
schema_migrations:
  import_db: CUSTOMERS_DB
  import_query: >
    SELECT *
    FROM schema_migrations
  export_db: EXPORT_DB
  export_schema: 'customers'
  export_table: 'schema_migrations'
  export_table_schema:
    version: character varying
  export_table_primary_key: version
