Required:
  - PG_ADDRESS
  - PG_PORT
  - PG_DATABASE
  - PG_USERNAME
  - PG_PASSWORD

  - VERSION_DB_USER
  - VERSION_DB_HOST
  - VERSION_DB_NAME

  - CUSTOMER_DB_USER
  - CUSTOMER_DB_HOST
  - CUSTOMER_DB_NAME

  - LICENSE_DB_USER
  - LICENSE_DB_HOST
  - LICENSE_DB_NAME
