version: 2

models:
    - name: fct_book_rating
      description: Data tracer bullet project which analyzes the book ratings of over 11k books.
      columns:
        - name: isbn13
          tests:
            - not_null
            - unique
        - name: isbn
            - not_null
            - unique
        - name: bookid
            - not_null
            - unique
        - name: ratings_count
            - not_null        
        - name: title
            - not_null
            - unique
