version: 2

models:
  - name: gitlab_dotcom_user_activation_events_monthly
    description: '{{ doc("gitlab_dotcom_user_activation_events_monthly") }}'
    columns:
      - name: user_id
        tests:
          - not_null
      - name: events_count
        tests:
          - not_null
  - name: gitlab_dotcom_user_issue_created_monthly
    description: '{{ doc("gitlab_dotcom_user_issue_created_monthly") }}'
    columns:
      - name: user_id
        tests:
          - not_null
      - name: events_count
        tests:
          - not_null
  - name: gitlab_dotcom_user_merge_request_opened_monthly
    description: '{{ doc("gitlab_dotcom_user_merge_request_opened_monthly") }}'
    columns:
      - name: user_id
        tests:
          - not_null
      - name: events_count
        tests:
          - not_null
  - name: gitlab_dotcom_user_project_created_monthly
    description: '{{ doc("gitlab_dotcom_user_project_created_monthly") }}'
    columns:
      - name: user_id
        tests:
          - not_null
      - name: events_count
        tests:
          - not_null
