version: 2
models:
  - name: xactly_credit_pii
  - name: xactly_pos_hierarchy_hist_pii
  - name: xactly_pos_part_assignment_pii
  - name: xactly_pos_part_assingment_hist_pii
  - name: xactly_pos_relations_hist_pii
  - name: xactly_pos_relations_pii
  - name: xactly_pos_title_assignment_hist_pii
  - name: xactly_pos_title_assignment_pii
  - name: xactly_quota_assignment_hist_pii
  - name: xactly_quota_assignment_pii