version: 2

models:
  - name: marketo_lead_source
    description: This table has marketo lead information.
    columns:
      - name: marketo_lead_id
        tests:
          - not_null
          - unique
  - name: marketo_activity_add_to_list_source
  - name: marketo_activity_add_to_nurture_source
  - name: marketo_activity_add_to_sfdc_campaign_source
  - name: marketo_activity_call_webhook_source
  - name: marketo_activity_change_data_value_source
  - name: marketo_activity_change_nurture_cadence_source
  - name: marketo_activity_change_nurture_track_source
  - name: marketo_activity_change_owner_source
  - name: marketo_activity_change_score_source
  - name: marketo_activity_change_segment_source
  - name: marketo_activity_change_status_in_progression_source
  - name: marketo_activity_change_status_in_sfdc_campaign_source
  - name: marketo_activity_click_email_source
  - name: marketo_activity_click_link_source
  - name: marketo_activity_convert_lead_source
  - name: marketo_activity_delete_lead_source
  - name: marketo_activity_email_bounced_soft_source
  - name: marketo_activity_email_bounced_source
  - name: marketo_activity_email_delivered_source
  - name: marketo_activity_execute_campaign_source
  - name: marketo_activity_fill_out_form_source
  - name: marketo_activity_fill_out_linkedin_lead_gen_form_source
  - name: marketo_activity_interesting_moment_source
  - name: marketo_activity_merge_leads_source
  - name: marketo_activity_new_lead_source
  - name: marketo_activity_open_email_source
  - name: marketo_activity_push_lead_to_marketo_source
  - name: marketo_activity_remove_from_list_source
  - name: marketo_activity_remove_from_sfdc_campaign_source
  - name: marketo_activity_request_campaign_source
  - name: marketo_activity_send_alert_source
  - name: marketo_activity_send_email_source
  - name: marketo_activity_sfdc_activity_source
  - name: marketo_activity_sfdc_activity_updated_source
  - name: marketo_activity_sync_lead_to_sfdc_source
  - name: marketo_activity_type_source
  - name: marketo_activity_unsubscribe_email_source
  - name: marketo_activity_update_opportunity_source
  - name: marketo_activity_visit_webpage_source