version: 1

models:
  - name: rpt_interviewee_satisfaction_isat
    description: This surfaces the greenhouse data for candidate surveys at a department level for interview SAT scores.
    columns:
    - name: candidate_survey_id
      tests:
      - not_null
      - unique
    - name: organization_id
      tests:
      - not_null
    - name: department_id
      tests:
      - not_null
    - name: department_name
      tests:
      - not_null
    - name: submitted_at
      tests:
      - not_null
    - name: candidate_survey_question_1
    - name: isat_score
  - name: rpt_greenhouse_all_openings
    description: Provides all job openings created in Greenhouse.
    columns: 
    - name: opening_id
    - name: job_title
    - name: job_opened_at
    - name: organization_name
  - name: rpt_greenhouse_hired_employees_opening
    description: For all hired employees, this report provides the job opening id for the job they were hired for,  in addition to the job title, department, and division they were hired in. Note - we will only have data for candidates that have an associated candidate_id in bamboohr. This data started being captured late 2019-12.
    columns:
    - name: employee_id
    - name: full_name
    - name: department
    - name: division
    - name: job_title
    - name: hire_date
    - name: greenhouse_candidate_id
    - name: opening_id
      description: This is the id associated to the job the employee was hired for. 
    - name: job_name