version: 1

models:
  - name: rpt_interviewee_satisfaction_isat
    description: This surfaces the greenhouse data for candidate surveys at a department level for interview SAT scores.
    columns:
    - name: candidate_survey_id
      tests:
      - not_null
      - unique
    - name: organization_id
      tests:
      - not_null
    - name: department_id
      tests:
      - not_null
    - name: department_name
      tests:
      - not_null
    - name: submitted_at
      tests:
      - not_null
    - name: candidate_survey_question_1
    - name: isat_score
  - name: greenhouse_diversity_lifecycle_gender
    description: Provides a breakdown of recruiting KPIs by gender.
    columns:
    - name: metric_month
    - name: gender
      tests: 
      - not_null
    - name: metric_total  
    - name: recruiting_metric
      description: Identifies which recruiting KPI the metric_total is related to. For example, the metric_total for where recruiting_metric is percent_of_applicants will show what percent of applicants were the gender in that row for that given month.
