version: 2

models:
  - name: mart_paid_subscription_monthly_counter_adoption
    description: '{{ doc("mart_paid_subscriptions_monthly_usage_ping_optin") }}'
    columns:
      - name: reporting_month
        tests:
            - not_null
      - name: pct_subscriptions_with_counters
        description: Percent of paid subscriptions that send us values for this specific counter. That means for a counter C releases in version V, all versions before V are excluded from this total
  - name: mart_paid_subscriptions_monthly_usage_ping_optin
    description: '{{ doc("mart_paid_subscriptions_monthly_usage_ping_optin") }}'
    columns:
      - name: month_subscription_id
        tests:
            - not_null
            - unique
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: subscription_name_slugify
        description: Unique key of a subscription
      - name: has_sent_payloads
        description: boolean flag to identify if for a specific month reporting_month and a specific subscription_name_slugify, a usage ping payload has been received.
      - name: latest_major_minor_version
        description: for a specific month reporting_month and a specific subscription_name_slugify, the latest version of the GitLab Application used.
