version: 2

models:
  - name: mart_monthly_product_usage
    description: '{{ doc("mart_monthly_product_usage") }}'
    tests:
      - unique:
          column_name: "concat(reporting_month, metrics_path, ping_id)"
    columns:
      - name: ping_id
        tests:
            - not_null
      - name: metrics_path
        description: The unique json path expression for a metrics in usage ping.
        tests:
            - not_null
      - name: main_edition
        description: The distribution of the gitlab instance, either EE or CE
        tests:
            - not_null
      - name: delivery
        description: SaaS or Self-Managed
        tests:
            - not_null
      - name: ping_product_tier
        description: The product tier the instance was on at the moment of the usage ping payload creation. A Ultimate ping_product_tier can be for example an OSS subscription, a real Ultimate subscription or a trial
        tests:
            - not_null
      - name: ping_product_tier
        description: The product tier the instance was on at the moment of the usage ping payload creation. A Ultimate ping_product_tier can be for example an OSS subscription, a real Ultimate subscription or a trial
        tests:
            - not_null
      - name: host_id
        description: The identifier of the host of the instance.
      - name: billing_account_id
        description: The zuora account id associated with the subscription. Use this field to join to dim_billing_accounts.
      - name: hostname
        description: The name of the host of the instance.
      - name: major_minor_version
        description: The version of the GitLab release on the instance (without the patch number). For example, 13.4. More details [here](https://docs.gitlab.com/ee/policy/maintenance.html)
      - name: major_version
        description: For example for Gitlab Version 13.5.2, `13` is the major version
      - name: is_pre_release
        description: Derived boolean flag noting if the version of GitLab on the instance corresponds to a pre-release or release candidate.
      - name: instance_user_count
        description: The total count of users on the instance.
      - name: is_trial
        description: Boolean flag noting if the license was generated as part of a trial.
      - name: created_at
        description: The timestamp when the usage ping was created.
        tests:
          - not_null
      - name: recorded_at
        description: The timestamp when the usage ping was recorded.
  - name: mart_usage_ping_counters_statistics
    description: '{{ doc("mart_usage_ping_counters_statistics") }}'
    tests:
      - unique:
          column_name: "concat(ping_name, edition)"
    columns:
      - name: ping_name
        tests:
            - not_null
  - name: mart_paid_subscriptions_monthly_usage_ping_optin
    description: '{{ doc("mart_paid_subscriptions_monthly_usage_ping_optin") }}'
    columns:
      - name: month_subscription_id
        tests:
            - not_null
            - unique
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: subscription_name_slugify
        description: Unique key of a subscription
      - name: has_sent_payloads
        description: boolean flag to identify if for a specific month reporting_month and a specific subscription_name_slugify, a usage ping payload has been received.
      - name: latest_major_minor_version
        description: for a specific month reporting_month and a specific subscription_name_slugify, the latest version of the GitLab Application used.
