wwright:
    can_login: yes
    is_superuser: no
    member_of:
        - readonly
    privileges:
        schemas:
            write:
                - historical
    owns:
        schemas:
          - wwright_scratch