version: 2

models:
    - name: xactly_credit_source
      columns:
        - name: participant_name
          meta:
            sensitive: true
        - name: position_name
          meta:
            sensitive: true
    - name: xactly_pos_hierarchy_hist
      columns:
        - name: from_pos_name
          meta:
            sensitive: true
        - name: to_pos_name
          meta:
            sensitive: true
    - name: xactly_pos_part_assignment
      columns:
        - name: participant_name
          meta:
            sensitive: true
        - name: position_name
          meta:
            sensitive: true
    - name: xactly_pos_part_assignment_hist
      columns:
        - name: participant_name
          meta:
            sensitive: true
        - name: position_name
          meta:
            sensitive: true
    - name: xactly_pos_relations
      columns:
        - name: from_pos_name
          meta:
            sensitive: true
        - name: to_pos_name
          meta:
            sensitive: true
    - name: xactly_pos_relations_hist
      columns:
        - name: from_pos_name
          meta:
            sensitive: true
        - name: to_pos_name
          meta:
            sensitive: true
    - name: xactly_pos_title_assignment
      columns:
        - name: position_name
          meta:
            sensitive: true
    - name: xactly_pos_title_assignment_hist
      columns:
        - name: position_name
          meta:
            sensitive: true
    - name: xactly_quota_assignment
      columns:
        - name: assignment_name
          meta:
            sensitive: true
    - name: xactly_quota_assignment_hist
      columns:
        - name: assignment_name
          meta:
            sensitive: true