version: 2

sources:
  - name: xactly
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_xactly
    loader: Stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: xc_credit
      - name: xc_pos_hierarchy_hist
      - name: xc_pos_part_assignment
      - name: xc_pos_part_assignment_hist
      - name: xc_pos_relations
      - name: xc_pos_relations_hist
      - name: xc_pos_title_assignment
      - name: xc_pos_title_assignment_hist
      - name: xc_quota_assignment
      - name: xc_quota_assignment_hist