# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
images:
  defaultbackend:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.0"
    pullPolicy: IfNotPresent
  nginxIngress:
    repository: gcr.io/google_containers/nginx-ingress-controller
    tag: "0.9.0-beta.15"
    pullPolicy: IfNotPresent
service:
  name: nginx
  type: LoadBalancer
  # loadBalancerIP (regional static IP in GKE to claim)
  ports:
  - http: 80
  - https: 443

hostName: bizops.example.com

proxyConnectTimeout: 15
proxyReadTimeout: 600
proxySendTimeout: 600
proxyBodySize: "512m"
hstsIncludeSubdomains: false
serverNameHashBucketSize: 256
