version: 2

models:
  - name: gitlab_dotcom_alert_management_http_integrations_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_analytics_cycle_analytics_group_stages_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_approval_merge_request_rule_sources_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_approval_project_rules_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_approval_project_rules_protected_branches_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_authentication_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_bulk_imports_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_cluster_agent_tokens_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_cluster_agents_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_cluster_providers_aws_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_cluster_providers_gcp_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_clusters_applications_cilium_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_container_expiration_policies_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_csv_issue_imports_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_grafana_integrations_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_group_import_states_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_issues_prometheus_alert_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_issues_self_managed_prometheus_alert_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_jira_imports_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_jira_tracker_data_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_ldap_group_links_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_lfs_file_locks_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_lfs_objects_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_operations_feature_flags_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_path_locks_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_pool_repositories_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_project_compliance_framework_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_project_error_tracking_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_project_feature_usages_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_project_incident_management_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_project_tracing_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_remote_mirrors_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_requirements_management_test_reports_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_security_scans_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_sentry_issues_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_status_page_published_incidents_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_status_page_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_suggestions_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_uploads_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_users_ops_dashboard_projects_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
  - name: gitlab_dotcom_zoom_meetings_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_docs") }}'
