version: 2

models:
  - name: bamboohr_currency_conversion
    description: This is the base model that transforms the currency conversion table. Note - this model is an ephemeral model.
  - name: bamboohr_ote
    description: This is the base model that transforms the ote table. Note - this model is an ephemeral model.
  - name: bamboohr_currency_promotions
    description: This data model joins on promotion data to identify what the change in comp is. Note - this model is an ephemeral model.
  - name: bamboohr_ote_promotions
    description: This data model joins on promotion data to identify the change in comp for team members that have variable pay. Note - this model is an ephemeral model.
  - name: bamboohr_promotions_xf
    description: This model joins the bamboohr_ote_promotions and bamboohr_currency_promotions data. In the case the team member is on variable pay we use the change in ote, otherwise we use the change in usd_annual_salary_amount.
