version: 2

models:
  - name: engineering_handbook_merge_requests
    description: This table is a base table for merge request data for the handbook GitLab project.
    columns:
      - name: file_diffs
      - name: merge_request_version_diffs
      - name: plain_diff_url_path
      - name: source_branch_name
  - name: handbook_file_classification_mapping
    description: This a csv loaded by dbt seed for mapping handbook file paths to divisions/department classifications.
