zuora_accounts_receivables:
    constraints:
        not_null:
            - invoice_id
        unique:
            - invoice_id

zuora_current_arr:
    constraints:
        not_null:
            - current_arr
