version: 2

models:
  - name: wip_fct_charge
    description: Fact table with recurring charge line item transactions. Non-recurring charges will be added in a future iteration.
    columns:
      - name: dim_subscription_id
        description: Unique identifier of a version of a subscription
        tests:
          - not_null
      - name: dim_charge_id
        description: The unique identifier of a rate plan charge
        tests:
          - not_null
          - unique
      - name: dim_product_detail_id
        description: The unique ID of a product rate plan charge
      - name: rate_plan_charge_number
        description: A unique number that identifies the charge
      - name: rate_plan_charge_name
        description: The name of the rate plan charge
      - name: effective_start_month
        description: Month when the segmented charge starts or started
      - name: effective_end_month
        description: Month when the segmented charge ends or ended
      - name: effective_start_date_id
        description: Id of the date when the segmented charge starts or started. Use this field to join to dim_date on id.
      - name: effective_end_date_id
        description: Id of the date when the segmented charge ends or ended. Use this field to join to dim_date on id.
      - name: effective_start_month_id
        description: Id of the month when the segmented charge starts or started. Use this field to join to dim_date on id.
      - name: effective_end_month_id
        description: Id of the month when the segmented charge ends or ended. Use this field to join to dim_date on id.
      - name: unit_of_measure
        description: Specifies the units to measure usage
      - name: quantity
        description: The default quantity of units
      - name: mrr
        description: Monthly recurring revenue (MRR) is the amount of recurring charges in a given month. The MRR calculation doesn't include one-time charges nor usage charges.
      - name: delta_tcv
        description: After an Amendment, the change in the total contract value (TCV) amount for this charge, compared with its previous value.
      - name: rate_plan_name
        description: The name of the rate plan
      - name: discount_level
        description: Specifies if the discount applies to just the product rate plan, the entire subscription, or to any activity in the account.
      - name: rate_plan_charge_segment
        description: The identifying number of the subscription rate plan segment. Segments are numbered sequentially, starting with 1.
      - name: rate_plan_charge_version
        description: The version of the rate plan charge. Each time a charge is amended, Zuora creates a new version of the rate plan charge.
      - name: charge_type
        description: Specifies the type of charge
  - name: wip_mart_waterfall
    description: Work in progress mart table replicating the waterfall report as seen in the Zuora Revenue UI. It shows how revenue is recognized over time for a given line item in a revenue contract. The grain of this table is as of period month - revenue contract line item - accounting segment - accounting type and can be summed to a higher grain if necessary.
    columns:
      - name: as_of_period_id
        description: The waterfall can be seen as of a certain time period. This column allows you to filter the waterfall report to how it appeared in a given month.
        tests:
          - not_null
      - name: book_name
        description: The unique identifier of an accounting book
      - name: organization_name
        description: The unique identifier of an organization in Zuora Revenue
      - name: revenue_contract_id
        description: The unique identifier of a revenue contract 
        tests:
          - not_null
      - name: revenue_contract_performance_obligation_name
        description: The unique identifier of one of the performance obligations attached to a revenue contract
        tests:
          - not_null
      - name: revenue_contract_line_id
        description: The unique identifier of a line item in a revenue contract 
        tests:
          - not_null
      - name: revenue_contract_customer_name
        description: The name of the customer for a given revenue contract line item 
        tests:
          - not_null
      - name: sales_order_number
        description: The unique identifier of a sales order.
      - name: sales_order_line_number
        description: The unique identifier of a line item in a sales order.
      - name: customer_number
        description: The unique identifier of a customer in both Zuora Revenue and Zuora Billing
      - name: accounting_segment
        description: The unique identifier of an accounting segment.
      - name: accounting_type_id
        description: The unique identifier of an accounting type
  - name: rpt_crm_opportunity_accepted_period
  - name: rpt_crm_opportunity_closed_period
  - name: rpt_crm_person_mql
  - name: rpt_main_ae_generated_cut
  - name: rpt_main_channel_generated_cut
  - name: rpt_main_order_type_cut
  - name: rpt_main_region_cut
  - name: rpt_main_regional_director_cut
  - name: rpt_main_sales_qualified_cut
  - name: rpt_main_sales_qualified_first_order_cut
  - name: rpt_main_sdr_generated_cut
  - name: rpt_main_web_direct_generated_cut
  - name: rpt_ratio_ae_generated_cut
  - name: rpt_ratio_channel_generated_cut
  - name: rpt_ratio_order_type_cut
  - name: rpt_ratio_regional_director_cut
  - name: rpt_ratio_sales_qualified_cut
  - name: rpt_ratio_sales_qualified_first_order_cut
  - name: rpt_ratio_sdr_generated_cut
  - name: rpt_ratio_web_generated_cut
  - name: rpt_sales_funnel_target_daily
  - name: rpt_sales_funnel_target

  - name: wk_finance_fct_recurring_charge_daily_snapshot
    description: Provides rate plan charge snapshots on a daily basis.
    columns:
      - name: charge_snapshot_id
        description: A primary key for daily rate_plan_charges at the subscription, charge_id grain.
        tests:
          - unique
          - not_null
  - name: wk_finance_mart_atr_myb_fy22_snapshot
    description: Provides a view into Multi-year bookings and available to renew ARR.
    columns:
      - name: charge_id
        description: A primary key for unique subscription charges.
        tests:
          - unique
          - not_null
  - name: prep_amendment_api_sandbox
    description: Prep table for Zuora Amendments that increment subscription versions. This prep table will be used in Facts and Dimensions.
    columns:
      - name: dim_amendment_id
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
  - name: prep_subscription_api_sandbox
    columns:
      - name: dim_subscription_id
        description: Unique identifier of a version of a subscription
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: dim_crm_account_id
        description: account id from SFDC identifing the customer
      - name: dim_billing_account_id
        description: The id of the Zuora account the subscription is associated with
      - name: dim_crm_person_id_invoice_owner
      - name: dim_crm_opportunity_id
      - name: dim_subscription_id_original
      - name: dim_subscription_id_previous
      - name: amendment_id
      - name: subscription_name_slugify
        description: The unique identifier of the subscription
      - name: subscription_status
        description: The status of the subscription
        tests:
          - not_null:
              severity: warn
          - accepted_values:
              values: ['Active', 'Cancelled', 'Draft', 'Expired']
      - name: subscription_version
        description: The version number of the subscription
      - name: is_auto_renew
        description: Boolean field, if true, this subscription automatically renews at the end of the subscription term
      - name: zuora_renewal_subscription_name
        description: name of the linked subscription that renews the prior subscription in a lineage
      - name: zuora_renewal_subscription_name_slugify
        description: name of the linked subscription that renews the prior subscription in a lineage
      - name: renewal_term
        description: The length of the period for the subscription renewal term
      - name: renewal_term_period_type
        description: The period type for the subscription renewal term. This field is used with the renewal term field to specify the subscription renewal term.
      - name: subscription_start_date
        description: The date when the subscription term starts. This date is the same as the start date of the original term, which isn't necessarily the start date of the current or new term.
      - name: subscription_end_date
        description: The date when the subscription term ends, where the subscription ends at midnight the day before. For example, if the SubscriptionEndDate is 12/31/2016, the subscriptions ends at midnight (00:00:00 hours) on 12/30/2016. This date is the same as the term end date or the cancelation date, as appropriate.
      - name: subscription_start_month
        description: The month when the subscription term starts. This month is the same as the start month of the original term, which isn't necessarily the start month of the current or new term.
      - name: subscription_end_month
        description: The month when the subscription term ends. This month is the same as the term end month or the cancelation month, as appropriate.
      - name: subscription_sales_type
        description: Identifies whether a subscription is Sales-Assisted or Self-Service / Web Direct.
        tests:
          - not_null:
              severity: warn
          - accepted_values:
                  values: ['Sales-Assisted', 'Self-Service']
      - name: is_myb
        description: MYB = Multi-Year Booking. This boolean flag identifies if a subscription is booked for more than one year. This can either be by having a term greater than 12 months or having a linked subscription.
      - name: is_myb_with_multi_subs
        description: MYB = Multi-Year Booking. This boolean flag identifies if a subscription is booked for more than one year by using multiple linked subscriptions only. A subscription with a term greater than 12 but does not have linked subscriptions has a value of FALSE.
  - name: dim_subscription_api_sandbox
    columns:
      - name: dim_subscription_id
        description: Unique identifier of a version of a subscription
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: dim_crm_account_id
        description: account id from SFDC identifing the customer
      - name: dim_billing_account_id
        description: The id of the Zuora account the subscription is associated with
      - name: dim_crm_person_id_invoice_owner
      - name: dim_crm_opportunity_id
      - name: dim_subscription_id_original
        tests:
          - not_null:
              severity: warn
      - name: dim_subscription_id_previous
      - name: amendment_id
      - name: subscription_name_slugify
        description: The unique identifier of the subscription
      - name: subscription_status
        description: The status of the subscription
        tests:
          - not_null:
              severity: warn
          - accepted_values:
              values: ['Active', 'Cancelled', 'Draft', 'Expired']
      - name: subscription_version
        description: The version number of the subscription
      - name: is_auto_renew
        description: Boolean field, if true, this subscription automatically renews at the end of the subscription term
      - name: zuora_renewal_subscription_name
        description: name of the linked subscription that renews the prior subscription in a lineage
      - name: zuora_renewal_subscription_name_slugify
        description: name of the linked subscription that renews the prior subscription in a lineage
      - name: renewal_term
        description: The length of the period for the subscription renewal term
      - name: renewal_term_period_type
        description: The period type for the subscription renewal term. This field is used with the renewal term field to specify the subscription renewal term.
      - name: subscription_start_date
        description: The date when the subscription term starts. This date is the same as the start date of the original term, which isn't necessarily the start date of the current or new term.
      - name: subscription_end_date
        description: The date when the subscription term ends, where the subscription ends at midnight the day before. For example, if the SubscriptionEndDate is 12/31/2016, the subscriptions ends at midnight (00:00:00 hours) on 12/30/2016. This date is the same as the term end date or the cancelation date, as appropriate.
      - name: subscription_start_month
        description: The month when the subscription term starts. This month is the same as the start month of the original term, which isn't necessarily the start month of the current or new term.
      - name: subscription_end_month
        description: The month when the subscription term ends. This month is the same as the term end month or the cancelation month, as appropriate.
      - name: subscription_sales_type
        description: Identifies whether a subscription is Sales-Assisted or Self-Service / Web Direct.
        tests:
          - not_null:
              severity: warn
          - accepted_values:
                  values: ['Sales-Assisted', 'Self-Service']
      - name: lineage
        description: "All the subscriptions subsquent to the primary subscription, separated by commas."
      - name: cohort_month
      - name: cohort_quarter
      - name: cohort_year
      - name: is_myb
        description: MYB = Multi-Year Booking. This boolean flag identifies if a subscription is booked for more than one year. This can either be by having a term greater than 12 months or having a linked subscription.
      - name: is_myb_with_multi_subs
        description: MYB = Multi-Year Booking. This boolean flag identifies if a subscription is booked for more than one year by using multiple linked subscriptions only. A subscription with a term greater than 12 but does not have linked subscriptions has a value of FALSE.
