version: 2

models:
  - name: wip_fct_charge
    description: Fact table with recurring charge line item transactions. Non-recurring charges will be added in a future iteration.
    columns:
      - name: dim_subscription_id
        description: Unique identifier of a version of a subscription
        tests:
          - not_null
      - name: dim_charge_id
        description: The unique identifier of a rate plan charge
        tests:
          - not_null
          - unique
      - name: dim_product_detail_id
        description: The unique ID of a product rate plan charge
      - name: rate_plan_charge_number
        description: A unique number that identifies the charge
      - name: rate_plan_charge_name
        description: The name of the rate plan charge
      - name: effective_start_month
        description: Month when the segmented charge starts or started
      - name: effective_end_month
        description: Month when the segmented charge ends or ended
      - name: effective_start_date_id
        description: Id of the date when the segmented charge starts or started. Use this field to join to dim_date on id.
      - name: effective_end_date_id
        description: Id of the date when the segmented charge ends or ended. Use this field to join to dim_date on id.
      - name: effective_start_month_id
        description: Id of the month when the segmented charge starts or started. Use this field to join to dim_date on id.
      - name: effective_end_month_id
        description: Id of the month when the segmented charge ends or ended. Use this field to join to dim_date on id.
      - name: unit_of_measure
        description: Specifies the units to measure usage
      - name: quantity
        description: The default quantity of units
      - name: mrr
        description: Monthly recurring revenue (MRR) is the amount of recurring charges in a given month. The MRR calculation doesn't include one-time charges nor usage charges.
      - name: delta_tcv
        description: After an Amendment, the change in the total contract value (TCV) amount for this charge, compared with its previous value.
      - name: rate_plan_name
        description: The name of the rate plan
      - name: discount_level
        description: Specifies if the discount applies to just the product rate plan, the entire subscription, or to any activity in the account.
      - name: rate_plan_charge_segment
        description: The identifying number of the subscription rate plan segment. Segments are numbered sequentially, starting with 1.
      - name: rate_plan_charge_version
        description: The version of the rate plan charge. Each time a charge is amended, Zuora creates a new version of the rate plan charge.
      - name: charge_type
        description: Specifies the type of charge
  - name: wip_mart_waterfall
    description: Work in progress mart table replicating the waterfall report as seen in the Zuora Revenue UI. It shows how revenue is recognized over time for a given line item in a revenue contract. The grain of this table is as of period month - revenue contract line item - accounting segment - accounting type and can be summed to a higher grain if necessary.
    columns:
      - name: as_of_period_id
        description: The waterfall can be seen as of a certain time period. This column allows you to filter the waterfall report to how it appeared in a given month.
        tests:
          - not_null
      - name: book_name
        description: The unique identifier of an accounting book
      - name: organization_name
        description: The unique identifier of an organization in Zuora Revenue
      - name: revenue_contract_id
        description: The unique identifier of a revenue contract 
        tests:
          - not_null
      - name: revenue_contract_performance_obligation_name
        description: The unique identifier of one of the performance obligations attached to a revenue contract
        tests:
          - not_null
      - name: revenue_contract_line_id
        description: The unique identifier of a line item in a revenue contract 
        tests:
          - not_null
      - name: revenue_contract_customer_name
        description: The name of the customer for a given revenue contract line item 
        tests:
          - not_null
      - name: sales_order_number
        description: The unique identifier of a sales order.
      - name: sales_order_line_number
        description: The unique identifier of a line item in a sales order.
      - name: customer_number
        description: The unique identifier of a customer in both Zuora Revenue and Zuora Billing
      - name: accounting_segment
        description: The unique identifier of an accounting segment.
      - name: accounting_type_id
        description: The unique identifier of an accounting type
  - name: rpt_crm_opportunity_accepted_period
  - name: rpt_crm_opportunity_closed_period
  - name: rpt_crm_person_mql
  - name: rpt_main_ae_generated_cut
  - name: rpt_main_channel_generated_cut
  - name: rpt_main_order_type_cut
  - name: rpt_main_region_cut
  - name: rpt_main_regional_director_cut
  - name: rpt_main_sales_qualified_cut
  - name: rpt_main_sales_qualified_first_order_cut
  - name: rpt_main_sdr_generated_cut
  - name: rpt_main_web_direct_generated_cut
  - name: rpt_ratio_ae_generated_cut
  - name: rpt_ratio_channel_generated_cut
  - name: rpt_ratio_order_type_cut
  - name: rpt_ratio_regional_director_cut
  - name: rpt_ratio_sales_qualified_cut
  - name: rpt_ratio_sales_qualified_first_order_cut
  - name: rpt_ratio_sdr_generated_cut
  - name: rpt_ratio_web_generated_cut
  - name: rpt_sales_funnel_target_daily
  - name: rpt_sales_funnel_target

  - name: wk_finance_fct_recurring_charge_daily_snapshot
    description: Provides rate plan charge snapshots on a daily basis.
    columns:
      - name: charge_snapshot_id
        description: A primary key for daily rate_plan_charges at the subscription, charge_id grain.
        tests:
          - unique
          - not_null
  - name: wk_finance_mart_atr_myb_fy22_snapshot
    description: Provides a view into Multi-year bookings and available to renew ARR.
    columns:
      - name: charge_id
        description: A primary key for unique subscription charges.
        tests:
          - unique
          - not_null
  - name: dim_product_detail_api_sandbox
    columns:
      - name: dim_product_detail_id
        description: The unique ID of each row in dim_product_detail, based on product rate plan charge ID.
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: dim_product_tier_id
        description: The unique ID of a product tier determined in dim_product_tier.
        tests:
          - not_null:
              severity: warn
      - name: product_id
        description: The ID of the product that contains the product rate plan.
        tests:
          - not_null:
              severity: warn
      - name: product_name
        description: The name of the product
      - name: is_reporter_license
        description: "Reporter licenses are in the Products with 'Additional Permission Types' in the name."
      - name: billing_list_price
        description: The price of the tier if the charge is a flat fee, or the price of each unit in the tier if the charge model is tiered pricing.
      - name: product_rate_plan_charge_id
        description: The unique ID of a product rate plan charge
      - name: product_rate_plan_name
        description: The name of the product rate plan. The name doesn't have to be unique in a Product Catalog, but the name has to be unique within a product.
      - name: product_rate_plan_charge_name
        description: The name of the product rate plan charge
      - name: product_sku
        description: The unique SKU for the product
      - name: product_tier_historical
        description: Product pricing tiers prior to [tier renaming](https://gitlab-com.gitlab.io/packaging-and-pricing/pricing-handbook/handbook/renaming_tiers/) (early 2021).
      - name: product_tier_historical_short
        description: Pulls the product tier from `product_tier_historical` with the delivery type removed
      - name: product_tier_name
        description: Product [pricing tiers](https://about.gitlab.com/handbook/marketing/strategic-marketing/tiers/) for both SaaS and Self-Managed customers. Includes the mapping from SaaS - Silver to SaaS - Premium, and from SaaS - Gold to SaaS - Ultimate.
      - name: product_tier_name_short
        description: Pulls the product tier from `product_tier_name` with the delivery type removed
      - name: effective_start_date
        description: The date when the product becomes available and can be subscribed to
      - name: effective_end_date
        description: The date when the product expires and can't be subscribed to anymore
      - name: is_oss_or_edu_rate_plan
        description: Flag for rate plans containing OSS or EDU
  - name: prep_product_detail_api_sandbox
    columns:
      - name: dim_product_detail_id
        description: The unique ID of each row in dim_product_detail, based on product rate plan charge ID.
      - name: dim_product_tier_id
        description: The unique ID of a product tier determined in dim_product_tier.
      - name: product_id
        description: The ID of the product that contains the product rate plan.
      - name: product_name
        description: The name of the product
      - name: is_reporter_license
        description: "Reporter licenses are in the Products with 'Additional Permission Types' in the name."
      - name: billing_list_price
        description: The price of the tier if the charge is a flat fee, or the price of each unit in the tier if the charge model is tiered pricing.
      - name: product_rate_plan_charge_id
        description: The unique ID of a product rate plan charge
      - name: product_rate_plan_name
        description: The name of the product rate plan. The name doesn't have to be unique in a Product Catalog, but the name has to be unique within a product.
      - name: product_rate_plan_charge_name
        description: The name of the product rate plan charge
      - name: product_sku
        description: The unique SKU for the product
      - name: product_tier_historical
        description: Product pricing tiers prior to [tier renaming](https://gitlab-com.gitlab.io/packaging-and-pricing/pricing-handbook/handbook/renaming_tiers/) (early 2021).
      - name: product_tier_historical_short
        description: Pulls the product tier from `product_tier_historical` with the delivery type removed
      - name: product_tier_name
        description: Product [pricing tiers](https://about.gitlab.com/handbook/marketing/strategic-marketing/tiers/) for both SaaS and Self-Managed customers. Includes the mapping from SaaS - Silver to SaaS - Premium, and from SaaS - Gold to SaaS - Ultimate.
      - name: product_tier_name_short
        description: Pulls the product tier from `product_tier_name` with the delivery type removed
      - name: effective_start_date
        description: The date when the product becomes available and can be subscribed to
      - name: effective_end_date
        description: The date when the product expires and can't be subscribed to anymore
      - name: is_oss_or_edu_rate_plan
        description: Flag for rate plans containing OSS or EDU
  - name: map_product_tier_api_sandbox
    columns:
      - name: product_rate_plan_id
        description: "Rate Plan ID for Zuora Product"
      - name: product_rate_plan_name
        description: "rate plan name from Zuora product source"
      - name: product_tier_historical
        description: Product pricing tiers prior to [tier renaming](https://gitlab-com.gitlab.io/packaging-and-pricing/pricing-handbook/handbook/renaming_tiers/) (early 2021).
        tests:
          - not_null:
              severity: warn
      - name: product_delivery_type
        description: "How product is delivered to customer; SaaS or Self-Managed (or Other)"
      - name: product_ranking
        description: "Numeric product pricing tier, independent of delivery type"
      - name: product_tier
        description: Product [pricing tiers](https://about.gitlab.com/handbook/marketing/strategic-marketing/tiers/) for both SaaS and Self-Managed customers. Includes the mapping from SaaS - Silver to SaaS - Premium, and from SaaS - Gold to SaaS - Ultimate.
        tests:
          - not_null:
              severity: warn
  - name: prep_product_tier_api_sandbox
    columns:
      - name: dim_product_tier_id
        description: "The unique identifier of Pricing tiers for Zuora Products"
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: product_tier_historical
        description: Product pricing tiers prior to [tier renaming](https://gitlab-com.gitlab.io/packaging-and-pricing/pricing-handbook/handbook/renaming_tiers/) (early 2021).
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: product_tier_historical_short
        description: Pulls the product tier from `product_tier_historical` with the delivery type removed
      - name: product_tier_name
        description: Product [pricing tiers](https://about.gitlab.com/handbook/marketing/strategic-marketing/tiers/) for both SaaS and Self-Managed customers. Includes the mapping from SaaS - Silver to SaaS - Premium, and from SaaS - Gold to SaaS - Ultimate.
        tests:
          - not_null:
              severity: warn
      - name: product_tier_name_short
        description: Pulls the product tier from `product_tier_name` with the delivery type removed
      - name: product_delivery_type
        description: "How product is delivered to customer; SaaS or Self-Managed (or Other)"
      - name: product_ranking
        description: "Numeric product pricing tier, independent of delivery type"
  - name: dim_billing_account_api_sandbox
    columns:
      - name: dim_billing_account_id
        description: Unique id of the Zuora account
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: dim_crm_account_id
        description: CRM account ID for the account
      - name: account_number
        description: A unique Zuora account number
      - name: account_name
        description: Zuora account name
      - name: account_status
        description: Status of the account in the system. Can be draft, active, cancelled.
      - name: parent_id
        description: Identifier of the parent customer account
      - name: sfdc_account_code
      - name: account_currency
        description: A currency as defined in Billing Settings in the Zuora UI
      - name: sold_to_country
        description: The country of the sold to contact
      - name: is_deleted
        description: flag indicating if account has been deleted
      - name: is_excluded
        description: Field used to exclude test accounts from downstream models
  - name: prep_recurring_charge_api_sandbox
    columns:
      - name: mrr_id
        description: The unique identifier of the MRR.
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: dim_date_id
        description: The identifier of date month in dim_date
      - name: dim_subscription_id
        description: The identifier of subscription in dim_subscriptions table
        tests:
          - not_null:
              severity: warn
      - name: dim_product_detail_id
        description: The identifier of product details in dim_product_detail
        tests:
          - not_null:
              severity: warn
      - name: dim_billing_account_id
        description: Zuora account id
      - name:  dim_crm_account_id
        description: account id frm crm
      - name: mrr
        description: Monthly Recurring Revenue value for given month
      - name: arr
        description: Annual Recurring Revenue value for given month
      - name: quantity
        description: Total quantity
  - name: fct_mrr_api_sandbox
    description: One row represents Monthly Recurring Revenue per month, by rate plan charge.
    columns:
      - name: mrr_id
        description: The unique identifier of the MRR.
        tests:
          - not_null:
              severity: warn
          - unique
      - name: dim_date_id
        description: The identifier of date month in dim_date
      - name: dim_charge_id
        description: join key for dim_charge
        tests:
          - not_null:
              severity: warn
      - name: dim_billing_account_id
        description: join key for dim_billing_account
        tests:
          - not_null:
              severity: warn
          - relationships:
              to: ref('dim_billing_account_api_sandbox')
              field: dim_billing_account_id
      - name: dim_crm_account_id
        description: join key for dim_crm_account
        tests:
          - relationships:
              to: ref('dim_crm_account')
              field: dim_crm_account_id
      - name: dim_subscription_id
        description: The identifier of subscription in dim_subscription table
        tests:
          - not_null:
              severity: warn
          - relationships:
              to: ref('dim_subscription_api_sandbox')
              field: dim_subscription_id
      - name: dim_product_detail_id
        description: The identifier of product details in dim_product_detail
        tests:
          - not_null:
              severity: warn
      - name: dim_billing_account_id
        description: Zuora account id
      - name:  dim_crm_account_id
        description: account id frm crm
      - name: mrr
        description: Monthly Recurring Revenue value for given month
      - name: arr
        description: Annual Recurring Revenue value for given month
      - name: quantity
        description: Total quantity
