version: 2

models:
  - name: feature_flags
    description: Source layer for a list of all feature flags
    columns:
      - name: name
      - name: type
      - name: group
      - name: milestone
      - name: default_enabled
