historical_metrics:
    constraints:
        not_null:
            - primary_key
        unique:
            - primary_key

historical_headcount:
    constraints:
        not_null:
            - primary_key
        unique:
            - primary_key

historical_sales_weekly_forecast:
    constraints:
        not_null:
            - primary_key
        unique:
            - primary_key