netsuite_accounts:
    constraints: 
        not_null: 
        - internal_account_id
        - account_name
        - account_type
        unique:
        - internal_account_id
        - account_name

netsuite_currencies:
    constraints: 
        not_null: 
        - currency_id
        - currency_name
        - currency_symbol
        - exchange_rate
        unique:
        - currency_id
        - currency_name
        - currency_symbol

netsuite_subsidiaries:
    constraints: 
        not_null: 
        - subsidiary_id
        - subsidiary_name
        - currency
        - country
        unique:
        - subsidiary_id
        - subsidiary_name

netsuite_transaction_lines:
    constraints: 
        not_null: 
        - transaction_line_id
        - transaction_id
        - transaction_line
        - account_id
        - account_name
        unique:
        - transaction_line_id

netsuite_vendors:
    constraints: 
        not_null: 
        - internal_vendor_id
        - entity_name
        unique:
        - internal_vendor_id
        - entity_name


