netsuite_accounts:
    constraints: 
        not_null: 
        - internal_account_id
        - account_name
        - account_type
        unique:
        - internal_account_id
        - account_name

netsuite_currencies:
    constraints: 
        not_null: 
        - currency_id
        - currency_name
        - currency_symbol
        - exchange_rate
        unique:
        - currency_id
        - currency_name
        - currency_symbol


netsuite_vendors:
    constraints: 
        not_null: 
        - internal_vendor_id
        - entity_name
        unique:
        - internal_vendor_id
        - entity_name

