version: 2

models:
    -   name: snowplow_gitlab_events_30
        description: This is is a view over the last 30 days of snowplow_gitlab_events_all based on the derived_tstamp column.
    -   name: snowplow_page_views_30
        description: This is is a view over the last 30 days of snowplow_page_views_all based on the page_view_start column.
