version: 2

models:
    - name: pings_active_instances
      description: instaces checked for new version or send a usage ping
      columns:
          - name: host_id
          - name: ping_type
            description: an instance checked for new version or send a usage ping
    - name: pings_usage_data_mom_change
      description: '{{ doc("pings_usage_data_mom_change") }}'
