version: 2

models:
    - name: pings_active_instances
      description: instaces checked for new version or send a usage ping
      columns:
          - name: host_id
          - name: ping_type
            description: an instance checked for new version or send a usage ping
