version: 2

models:
  - name: fct_mrr_snapshot_model
    description: '{{ doc("fct_mrr_snapshot_model") }}'

  - name: dim_subscription_snapshot_model
    description: '{{ doc("dim_subscription_snapshot_model") }}'

  - name: fct_retention_parent_account_snapshot_model
    description: '{{ doc("fct_retention_parent_account_snapshot_model") }}'
