version: 2

models:
    -   name: snowplow_event_counts
        description: This model counts good and bad events by day.
        columns:
            -   name: event_day
                tests:
                    - not_null
                    - unique

