connection_info:
  user: CI_STATS_DB_USER
  pass: CI_STATS_DB_PASS
  host: CI_STATS_DB_HOST
  database: CI_STATS_DB_NAME
  port: PG_PORT
tables:
  spec_profiling_results:
    import_db: CI_STATS_DB
    import_query: >
      SELECT id
      , commit
      , date
      , file
      , line_number
      , description
      , time as spec_time
      , status
      , exception
      , query_count
      , query_time
      , request_count
      , request_time
      , created_at
      , updated_at
      , branch
      FROM spec_profiling_results
      WHERE updated_at BETWEEN TO_TIMESTAMP('{EXECUTION_DATE}', 'YYYY-MM-DDTHH:MI:SS+00:00') - interval '{HOURS} hour'
        AND TO_TIMESTAMP('{EXECUTION_DATE}', 'YYYY-MM-DDTHH:MI:SS+00:00')
    export_schema: 'ci_stats'
    export_table: 'spec_profiling_results'
    export_table_primary_key: id
