version: 2

sources:
  - name: snowflake
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: snowflake
    loader: Airflow
    loaded_at_field: to_timestamp_ntz(_uploaded_at::number)
    
    quoting:
      database: true
      identifier: false
      schema: false

    freshness:
        warn_after: {count: 1, period: day}

    tables:
      - name: user_roles