version: 2
models:
  - name: sfdc_account
    description: base model for SFDC Accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: account_name
        tests:
          - not_null

  - name: sfdc_bizible_attribution_touchpoint
    description: base model for Bizible attribution touch points that are pushed into SFDC
    columns:
        - name: touchpoint_id
          tests:
              - not_null
              - unique
        - name: campaign_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_campaign')
                    field: campaign_id

  - name: sfdc_campaign
    description: base model for SFDC Campaigns
    columns:
        - name: campaign_id
          tests:
              - not_null
              - unique
        - name: campaign_name
          tests:
              - not_null

  - name: sfdc_contact
    description: base model for SFDC Contacts
    columns:
        - name: contact_id
          tests:
              - not_null
              - unique
        - name: contact_name
          tests:
              - not_null

  - name: sfdc_executive_business_review
    description: base model for SFDC Executive Business Reviews
    columns:
        - name: account_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_account')
                    field: account_id
        - name: ebr_id
          tests:
              - not_null
              - unique
        - name: ebr_date
          tests:
              - not_null
        - name: owner_id
          tests:
              - not_null
        - name: ebr_name
          tests:
              - not_null

  - name: sfdc_lead
    description: base model for SFDC Leads
    columns:
        - name: lead_id
          tests:
              - not_null
              - unique
        - name: lead_name
          tests:
              - not_null

  - name: sfdc_opportunity
    description: base model for SFDC Opportunities
    columns:
        - name: account_id
          tests:
              - not_null
        - name: opportunity_id
          tests:
              - not_null
              - unique
        - name: opportunity_name
          tests:
              - not_null
        - name: stage_name
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_opportunitystage')
                    field: primary_label

  - name: sfdc_opportunity_line_item
    description: base model for SFDC Opportunity Line Items
    columns:
        - name: opportunity_line_item_id
          tests:
              - not_null
              - unique
        - name: opportunity_line_item_name
          tests:
              - not_null

  - name: sfdc_opportunityhistory
    description: base model for SFDC Opportunity History
    columns:
        - name: id
          tests:
              - not_null
              - unique
        - name: opportunityid
          tests:
              - not_null

  - name: sfdc_opportunitystage
    description: base model for SFDC Opportunity Stages
    columns:
        - name: sfdc_id
          tests:
              - not_null
              - unique
        - name: stage_id
          tests:
              - not_null
              - unique

  - name: sfdc_record_type
    description: base model for SFDC Record Types
    columns:
        - name: record_type_id
          tests:
              - not_null
              - unique
        - name: record_type_name
          tests:
              - not_null

  - name: sfdc_proof_of_concept
    description: base model for SFDC Proof of Concept
    columns:
        - name: account_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_account')
                    field: account_id
        - name: opportunity_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_opportunity')
                    field: opportunity_id
        - name: poc_id
          tests:
              - not_null
              - unique
        - name: poc_status
          tests:
              - not_null

  - name: sfdc_snapshot_opportunity
    description: A table containing snapshotted historical data of the sfdc_opportunity table
    columns:
        - name: sfdc_opportunity_id
          description: This is a unique identifier for the event
          tests:
              - not_null
        - name: snapshot_date
          description: "The date this  occurred in America/Los_Angeles time (eg. 2018-01-01)"
          tests:
              - not_null
        - name: owner_id
          description: The ID of the user who recorded the event
          tests:
              - not_null


  - name: sfdc_statement_of_work
    description: base model for SFDC Statements of Work
    columns:
        - name: statement_of_work_id
          tests:
              - not_null
              - unique
        - name: opportunity_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_opportunity')
                    field: opportunity_id

  - name: sfdc_user_roles
    description: base model for SFDC User Roles
    columns:
        - name: id
          tests:
              - not_null
              - unique

  - name: sfdc_users
    description: base model for SFDC Users
    columns:
        - name: id
          tests:
              - not_null
              - unique