version: 2
models:
- name: sfdc_account
  columns:
  - name: account_id
    tests:
    - not_null
    - unique
  - name: account_name
    tests:
    - not_null
- name: sfdc_bizible_attribution_touchpoint
  columns:
  - name: touchpoint_id
    tests:
    - not_null
    - unique
- name: sfdc_campaign
  columns:
  - name: campaign_id
    tests:
    - not_null
    - unique
  - name: campaign_name
    tests:
    - not_null
- name: sfdc_contact
  columns:
  - name: contact_id
    tests:
    - not_null
    - unique
  - name: contact_name
    tests:
    - not_null
- name: sfdc_executive_business_review
  columns:
  - name: account_id
    tests:
    - not_null
  - name: ebr_date
    tests:
    - not_null
  - name: ebr_id
    tests:
    - not_null
    - unique
  - name: ebr_name
    tests:
    - not_null
  - name: owner_id
    tests:
    - not_null
- name: sfdc_lead
  columns:
  - name: lead_id
    tests:
    - not_null
    - unique
  - name: lead_name
    tests:
    - not_null
- name: sfdc_opportunity
  columns:
  - name: account_id
    tests:
    - not_null
  - name: opportunity_id
    tests:
    - not_null
    - unique
  - name: opportunity_name
    tests:
    - not_null
- name: sfdc_opportunity_line_item
  columns:
  - name: opportunity_line_item_id
    tests:
    - not_null
    - unique
  - name: opportunity_line_item_name
    tests:
    - not_null
- name: sfdc_opportunityhistory
  columns:
  - name: id
    tests:
    - not_null
    - unique
  - name: opportunityid
    tests:
    - not_null
- name: sfdc_opportunitystage
  columns:
  - name: sfdc_id
    tests:
    - not_null
    - unique
  - name: stage_id
    tests:
    - not_null
    - unique
- name: sfdc_record_type
  columns:
  - name: record_type_id
    tests:
    - not_null
    - unique
  - name: record_type_name
    tests:
    - not_null
- name: sfdc_proof_of_concept
  columns:
  - name: account_id
    tests:
    - not_null
  - name: opportunity_id
    tests:
    - not_null
  - name: poc_id
    tests:
    - not_null
    - unique
  - name: poc_status
    tests:
    - not_null
- name: sfdc_statement_of_work
  columns:
  - name: opportunity_id
    tests:
    - not_null
  - name: statement_of_work_id
    tests:
    - not_null
    - unique
- name: sfdc_user_roles
  columns:
  - name: id
    tests:
    - not_null
    - unique
- name: sfdc_users
  columns:
  - name: id
    tests:
    - not_null
    - unique
