version: 2

models:
  - name: bamboohr_base_mapping
    description: This model ties all departments to the last 12 months and is used in downstream models to do rolling 12 month metrics

  - name: bamboohr_budget_vs_actual
    description: Compares promotion budget spend to the budget aggregated at the division level.
    columns:
    - name: fiscal_quarter_name
    - name: division
    - name: fiscal_year
    - name: fiscal_quarter
    - name: budget
    - name: excess_from_previous_quarter
    - name: total_spend

  - name: bamboohr_id_employee_number_mapping
    description: This model is the canonical source mapping bamboo employee numbers with employee IDs. It includes all employees for all time. The model also captures demographic information, and removes test accounts.
    columns:
      - name: employee_id
        test: 
          - not_null
          - unique
      - name: employee_number
        test:
          - not_null
          - unique
      - name: first_name
      - name: last_name
      - name: hire_date
      - name: termination_date
      - name: age_cohort
        description: As based on current data.  
      - name: gender
      - name: nationality
      - name: region
      - name: region_modified
        description: Identifies if employee is in NORAM, LATAM, EMEA, or JAPAC region
      - name: gender_region
      - name: greenhouse_candidate_id
        description: Captures the id associated to the employee in Greenhouse (our recruiting platform). This will only be applicable in Greenhouse starting 2019-12-13, and will help identify which candidates were hired.
        tests: 
            - unique     
