dim_opphistory:
    constraints:
        not_null:
            - dim_opphistory_id

sfdc_sales_accepted_opportunity:
    constraints:
        not_null:
            - opportunity_segment
            - opportunity_name

sfdc_accounts_xf:
    constraints:
        not_null:
            - account_id
            - account_name
        unique:

sfdc_bizible_attribution_touchpoint_xf:
    constraints:
        not_null:
            - touchpoint_id
            - campaign_id
        unique:
            - touchpoint_id

sfdc_proof_of_concept_xf:
    constraints:
        not_null:
            - poc_id
            - account_id
            - opportunity_id
            - poc_status
        unique:
            - poc_id

sfdc_statement_of_work_xf:
    constraints:
        not_null:
            - statement_of_work_id
        unique:
            - statement_of_work_id

users:
    constraints:
        unique:
            - id