version: 2

models:
  - name: team_yaml_historical
    description: This is the base table built on the snapshots of the [team.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/team.yml) in the GitLab Handbook.
    columns:
      -   name: snapshot_date
          tests:
            - not_null
  - name: team_yaml_latest
    description: This is the latest version of the [team.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/team.yml) in the GitLab Handbook, pulled from the historical base table.
    columns:
      -   name: snapshot_date
          tests:
            - not_null