version: 2

models:
  - name: zuora_accounts_new_updated
    description: '{{ doc("zuora_accounts_new_updated") }}'
    columns:
      - name: date_day
        tests:
          - not_null
  - name: zuora_subscriptions_new_updated
    description: '{{ doc("zuora_subscriptions_new_updated") }}'
    columns:
      - name: date_day
        tests:
          - not_null
  - name: zuora_golden_records
    description: '{{ doc("zuora_golden_records") }}'
    columns:
      - name: account_name
        meta:
          sensitive: true
      - name: account_type
        meta:
          sensitive: true
      - name: mrr
        meta:
          sensitive: true
      - name: mrr
        meta:
          sensitive: true
      - name: subscription_start_date
        meta:
          sensitive: true
      - name: product_sku
        meta:
          sensitive: true
      - name: unit_of_measure
        meta:
          sensitive: true
      - name: quantity
        meta:
          sensitive: true