version: 2

models:
  - name: fct_usage_ping_metrics_status
    description: fct table that gets statistics for the metrics. to understand if the metrics succeeded and failed and how many rows we have per metrics
