version: 2

models:
    - name: ping_stat_to_stage_mapping
      description: mapping of metrics in the pings data to a stage. The data for this base model must be populated using `dbt seed`

    - name: pings_avg_cycle_analytics
      description: Ping data from Self-Managed users.
      columns:
         - name: avg_cycle_analytics_id
           tests:
               - not_null

    - name: pings_hosts
      columns:
          - name: host_id
            tests:
                - not_null

    - name: pings_licenses
      columns:
          - name: license_id
            tests:
                - not_null

    - name: pings_usage_data
      columns:
          - name: uuid
            tests:
                - not_null

    - name: pings_version_checks
      description: Ping version data from self-managed instances
      columns:
          - name: id
            tests:
                - not_null
                - unique
          - name: host_id
            tests:
                - not_null