version: 2

models:
    - name: cleaned_urls
    - name: clearbit_cache
    - name: discoverorg_cache
    - name: pings_avg_cycle_analytics_tappg
      description: '{{ doc("tappg_model") }}'
    - name: pings_avg_cycle_analytics_version
      description: '{{ doc("version_model") }}'
    - name: pings_usage_data_tappg
      description: '{{ doc("tappg_model") }}'
    - name: pings_usage_data_version
      description: '{{ doc("version_model") }}'
    - name: pings_version_checks_tappg
      description: '{{ doc("tappg_model") }}'
    - name: pings_version_checks_version
      description: '{{ doc("version_model") }}'
    - name: whois_cache