version: 2

sources:
  - name: pings_tap_postgres
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_postgres
    loaded_at_field: _uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: avg_cycle_analytics
        identifier: version_db_avg_cycle_analytics
        columns:
          - name: id
            tests:
              - not_null
      - name: usage_data
        identifier: version_db_usage_data
        columns:
          - name: id
            tests:
              - not_null
      - name: version_checks
        identifier: version_db_version_checks
        columns:
          - name: id
            tests:
              - not_null
