version: 2

models:
  - name: dim_accounts
    description: "Dimension table representing each individual account with details of person to bill for the account. Excludes deleted and test accounts"

  - name: dim_dates

  - name: dim_subscriptions
    description: "Dimension table representing subscription details as in Zuora"
    columns:
      - name: subscription_status
        tests:
          - not_null

  - name: dim_products
    description: "Product related information for which account is charged "

  - name: fct_invoice_items_agg
    description: "Aggregate fact table with invoice items summarized on charge level"
    columns:
      - name: charge_id
        tests:
          - not_null
          - unique

  - name: fct_charges
    description: "Factual table with all rate plan charges coming from subscriptions or an amendment to a subscription"
    columns:
      - name: subscription_id
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null





