version: 2

models:
  - name: datasiren_canary_sensor
  - name: datasiren_prod_boneyard_email_value_sensor
  - name: datasiren_prod_common_email_value_sensor
  - name: datasiren_prod_common_mapping_email_value_sensor
  - name: datasiren_prod_legacy_email_value_sensor
  - name: datasiren_source_db_social_security_number_sensor
  - name: datasiren_transform_db_email_value_sensor
  - name: datasiren_transform_db_ip_address_sensor