version: 2

models:
  - name: wk_self_managed_spo
    description: Workspace model that builds a MVC for Self-Managed SPO and SPU KPIs.
    columns:
      - name: organization_id
        description: Top-level namespace id.
        tests:
          - not_null
      - name: delivery
        description: delivery is based on the product category name.
        tests:
          - not_null
      - name: organization_type
        description: segmentation for organization type. Values - Group, Individual, User
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual']
      - name: active_stage_count
        description: number of active stages for a given organization in a given month


  - name: wk_saas_spo
    description: Workspace model that shows monthly Stages per Organization data on a namespace-level for SaaS.
    columns:
      - name: reporting_month
        description: Month in which the product usage was reported.
        tests:
          - not_null
      - name: organization_id
        description: Top-level namespace id.
        tests:
          - not_null
      - name: delivery
        description: delivery is based on the product category name.
        tests:
          - not_null
      - name: organization_type
        description: segmentation for organization type. Values - Group, Individual, User
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual','User']
      - name: product_tier
        description: segmentation for Product Tier. Values - Core (CE, EE), Starter, Premium, Ultimate, NULL
        tests:
          - not_null
      - name: is_paid_product_tier
        description: information on whether the product tier has been paid for or not
        tests:
          - not_null
      - name: active_stage_count
        description: number of active stages for a given organization in a given month

  - name: wk_usage_ping_geo_node_usage
    description: Extract and flatten data from the geo nodes
    columns:
      - name: instance_path_id
        description: the unique ID for an instance path.
        tests:
          - not_null
          - unique

  - name: fct_usage_event
    description: ' {{ doc("fct_usage_event") }} '
    columns:
      - name: event_id
        description: The unique ID of an event.
        tests:
          - not_null
          - unique

  - name: mart_usage_event
    description: ' {{ doc("mart_usage_event") }} '
    columns:
      - name: event_id
        description: The unique ID of an event.
        tests:
          - not_null
          - unique

  - name: mart_usage_namespace_daily
    description: ' {{ doc("mart_usage_namespace_daily") }} '
    columns:
      - name: mart_usage_namespace_id
        description: the unique ID of a usage namespace in mart_usage_namespace
        tests:
          - not_null
          - unique

  - name: mart_usage_instance_daily
    description: ' {{ doc("mart_usage_instance_daily") }} '
    columns:
      - name: mart_usage_instance_id
        description: the unique ID of a usage instance in mart_usage_instance
        tests:
          - not_null
          - unique

  - name: mart_usage_event_daily
    description: ' {{ doc("mart_usage_event_daily") }} '
    columns:
      - name: mart_usage_event_daily_id
        description: the unique ID of a daily usage event in mart_usage_event_daily
        tests:
          - not_null
          - unique

  - name: mart_usage_event_plan_monthly
    description: ' {{ doc("mart_usage_event_plan_monthly") }} '
    columns:
      - name: mart_usage_event_plan_monthly_id
        description: the unique ID of a montthly usage event plan in mart_usage_event_plan_monthly
        tests:
          - not_null
          - unique

  - name: mart_xmau_metric_monthly
    description: ' {{ doc("mart_xmau_metric_monthly") }} '
    columns:
      - name: mart_xmau_metric_monthly_id
        description: the unique ID of a montthly xMAU metric in mart_xmau_metric_monthly 
        tests:
          - not_null
          - unique
