version: 2

models:
  - name: wk_self_managed_spo
    description: Workspace model that builds a MVC for Self-Managed SPO and SPU KPIs.
    columns:
      - name: organization_id
        description: Top-level namespace id.
        tests:
          - not_null
      - name: delivery
        description: delivery is based on the product category name and is either SaaS or Self-Managed delivery.
        tests:
          - not_null
      - name: organization_type
        description: segmentation for organization type. Values - Group, Individual, User
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual']
      - name: active_stage_count
        description: number of active stages for a given organization in a given month


  - name: wk_saas_spo
    description: Workspace model that shows monthly Stages per Organization data on a namespace-level for SaaS.
    columns:
      - name: reporting_month
        description: Month in which the product usage was reported.
        tests:
          - not_null
      - name: organization_id
        description: Top-level namespace id.
        tests:
          - not_null
      - name: delivery
        description: delivery is based on the product category name and is either SaaS or Self-Managed delivery.
        tests:
          - not_null
      - name: organization_type
        description: segmentation for organization type. Values - Group, Individual, User
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual','User']
      - name: product_tier
        description: segmentation for Product Tier. Values - Core (CE, EE), Starter, Premium, Ultimate, NULL
        tests:
          - not_null
      - name: is_paid_product_tier
        description: information on whether the product tier has been paid for or not
        tests:
          - not_null
      - name: active_stage_count
        description: number of active stages for a given organization in a given month

  - name: wk_usage_ping_geo_node_usage
    description: Extract and flatten data from the geo nodes
    columns:
      - name: instance_path_id
        description: the unique ID for an instance path.
        tests:
          - not_null
          - unique
      

  - name: fct_usage_event
    description: ' {{ doc("fct_usage_event") }} '
    columns:
      - name: event_id
        description: The unique ID of an event.
        tests:
          - not_null
          - unique
      - name: event_name
        description: The name tied to an event
      - name: dim_instance_id
        description: The unique id of an instance from the dim_instance model.
      - name: dim_product_tier_id
        description: The unique id of a Product Tier in the dim_product_tier model.
      - name: dim_subscripton_id
        description: The unique id of a subscription from the dim_subscription model
      - name: dim_event_date_id
        description: The unique id of an instance from the dim_event_date model.
      - name: dim_crm_account_id
        description: The unique id of a crm account in the dim_crm_account model.
      - name: dim_billing_account_id
        description: The unqiue id of a billing account in the dim_billing_account model.
      - name: dim_namespace_id
        description: The unique id of a namespace from the dim_namespace model.
      - name: dim_project_id
        description: The unique id of a project from the dim_project model.
      - name: dim_user_id
        description: The unique id of a user from the dim_user model.
      - name: stage_name
        description: The name of the assigned stage.
      - name: section_name
        description: The name of the assigned section.
      - name: group_name
        description: The name of the assigned group
      - name: event_created_at
        description: The date at which the event was created
      - name: plan_id_at_event_date
        description: The id of the plan when the event was created.
      - name: plan_name_at_event_date
        description: The name of the plan type when the event was created
      - name: plan_was_paid_at_event_date
        description: Defines whether the plan was paid for when the event was created
      - name: project_is_learn_gitlab
        description: Does this project relate to Learn GitLab?
      - name: data_source
        description: The location that this data is being stored
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated

  - name: mart_usage_event
    description: ' {{ doc("mart_usage_event") }} '
    columns:
      - name: event_id
        description: The unique ID of an event.
        tests:
          - not_null
          - unique
      - name: event_date
        description: The date when the event was created.
      - name: dim_user_id
        description: The unique id of a user in the dim_user model.
      - name: event_name
        description: The name tied to an event
      - name: dim_product_tier_id
        description: The unique id of a Product Tier in the dim_product_tier model.
      - name: dim_subscripton_id
        description: The unique id of a subscription from the dim_subscription model
      - name: dim_crm_account_id
        description: The unique id of a crm account in the dim_crm_account model.
      - name: dim_billing_account_id
        description: The unqiue id of a billing account in the dim_billing_account model.
      - name: stage_name
        description: The name of the assigned stage.
      - name: section_name
        description: The name of the assigned section.
      - name: group_name
        description: The name of the assigned group
      - name: data_source
        description: The location that this data is being stored
      - name: plan_id_at_event_date
        description: The id of the plan when the event was created.
      - name: plan_name_at_event_date
        description: The name of the plan type when the event was created
      - name: plan_was_paid_at_event_date
        description: Defines whether the plan was paid for when the event was created
      - name: dim_namespace_id
        description: The unique id of a namespace from the dim_namespace model.
      - name: dim_instance_id
        description: The unique id of an instance from the dim_instance model.
      - name: namespace_created_at
        description: The date when the namespace was created.
      - name: days_since_namespace_created
        description: The difference in days since the namespace was created
      - name: is_smau
        description: Is this event part of the stage monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_gmau
        description: Is this event part of the group active monthly user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_umau
        description: Is this event part of the unique monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated
        

  - name: mart_usage_namespace_daily
    description: ' {{ doc("mart_usage_namespace_daily") }} '
    columns:
      - name: mart_usage_namespace_id
        description: the unique ID of a usage namespace in mart_usage_namespace
        tests:
          - not_null
          - unique
      - name: event_date
        description: The date when the event was created.
      - name: event_name
        description: The name tied to an event
      - name: dim_product_tier_id
        description: The unique id of a Product Tier in the dim_product_tier model.
      - name: dim_subscripton_id
        description: The unique id of a subscription from the dim_subscription model
      - name: dim_crm_account_id
        description: The unique id of a crm account in the dim_crm_account model.
      - name: dim_billing_account_id
        description: The unqiue id of a billing account in the dim_billing_account model.
      - name: stage_name
        description: The name of the assigned stage.
      - name: section_name
        description: The name of the assigned section.
      - name: group_name
        description: The name of the assigned group
      - name: data_source
        description: The location that this data is being stored
      - name: plan_id_at_event_date
        description: The id of the plan when the event was created.
      - name: plan_name_at_event_date
        description: The name of the plan type when the event was created
      - name: plan_was_paid_at_event_date
        description: Defines whether the plan was paid for when the event was created
      - name: dim_instance_id
        description: The unique id of an instance from the dim_instance model.
      - name: dim_namespace_id
        description: The unique id of a namespace from the dim_namespace model.
      - name: namespace_created_at
        description: The date when the namespace was created.
      - name: days_since_namespace_created
        description: The difference in days since the namespace was created
      - name: is_smau
        description: Is this event part of the stage monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_gmau
        description: Is this event part of the group active monthly user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_umau
        description: Is this event part of the unique monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: event_count
        description: The count of events
      - name: distinct_user_count
        description: The count of distinct users
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated

  - name: mart_usage_instance_daily
    description: ' {{ doc("mart_usage_instance_daily") }} '
    columns:
      - name: mart_usage_instance_id
        description: the unique ID of a usage instance in mart_usage_instance
        tests:
          - not_null
          - unique
      - name: event_date
        description: The date when the event was created.
      - name: event_name
        description: The name tied to an event
      - name: data_source
        description: The location that this data is being stored
      - name: dim_instance_id
        description: The unique id of an instance from the dim_instance model.
      - name: event_count
        description: The count of events
      - name: distinct_user_count
        description: The count of distinct users
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated

  - name: mart_usage_event_daily
    description: ' {{ doc("mart_usage_event_daily") }} '
    columns:
      - name: mart_usage_event_daily_id
        description: the unique composite ID for the mart_usage_event_daily model consisting of event_date, dim_user_id, dim_namespace_id, and event_name.
        tests:
          - not_null
          - unique
      - name: event_date
        description: The date when the event was created.
      - name: dim_user_id
        description: The unique id of a user in the dim_user model.
      - name: dim_namespace_id
        description: The unique id of a namespace from the dim_namespace model.
      - name: dim_instance_id
        description: The unique id of an instance from the dim_instance model.
      - name: plan_id_at_event_date
        description: The id of the plan when the event was created.
      - name: event_name
        description: The name tied to an event
      - name: dim_product_tier_id
        description: The unique id of a Product Tier in the dim_product_tier model.
      - name: dim_subscripton_id
        description: The unique id of a subscription from the dim_subscription model
      - name: dim_crm_account_id
        description: The unique id of a crm account in the dim_crm_account model.
      - name: dim_billing_account_id
        description: The unqiue id of a billing account in the dim_billing_account model.
      - name: stage_name
        description: The name of the assigned stage.
      - name: section_name
        description: The name of the assigned section.
      - name: group_name
        description: The name of the assigned group
      - name: data_source
        description: The location that this data is being stored
      - name: plan_name_at_event_date
        description: The name of the plan type when the event was created
      - name: plan_was_paid_at_event_date
        description: Defines whether the plan was paid for when the event was created
      - name: namespace_is_internal
        description: Tells whether this namespace is internal or not
      - name: namespace_created_at
        description: The date when the nampespace was created.
      - name: days_since_namespace_created
        description: The difference in days since the namespace was created
      - name: is_smau
        description: Is this event part of the stage monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_gmau
        description: Is this event part of the group active monthly user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_umau
        description: Is this event part of the unique monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: event_count
        description: The count of events
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated

  - name: mart_usage_event_plan_monthly
    description: ' {{ doc("mart_usage_event_plan_monthly") }} '
    columns:
      - name: mart_usage_event_plan_monthly_id
        description: the unique ID of a montthly usage event plan in mart_usage_event_plan_monthly
        tests:
          - not_null
          - unique
      - name: reporting_month
        description: Month in which the product usage was reported.
      - name: plan_id_at_event_date
        description: The id of the plan when the event was created.
      - name: event_name
        description: The name tied to an event
      - name: stage_name
        description: The name of the assigned stage.
      - name: section_name
        description: The name of the assigned section.
      - name: group_name
        description: The name of the assigned group
      - name: is_smau
        description: Is this event part of the stage monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_gmau
        description: Is this event part of the group active monthly user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_umau
        description: Is this event part of the unique monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: event_count
        description: The count of events
      - name: namespace_count
        description: The count of namespaces
      - name: user_count
        description: The count of users
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated

  - name: mart_xmau_metric_monthly
    description: ' {{ doc("mart_xmau_metric_monthly") }} '
    columns:
      - name: mart_xmau_metric_monthly_id
        description: the unique ID of a montthly xMAU metric in mart_xmau_metric_monthly 
        tests:
          - not_null
          - unique
      - name: reporting_month
        description: Month in which the product usage was reported.
      - name: is_smau
        description: Is this event part of the stage monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_gmau
        description: Is this event part of the group active monthly user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: is_umau
        description: Is this event part of the unique monthly active user slice? See [Page](https://internal-handbook.gitlab.io/product/performance-indicators/#structure) for metric definitions
      - name: stage_name
        description: The name of the assigned stage.
      - name: section_name
        description: The name of the assigned section.
      - name: group_name
        description: The name of the assigned group
      - name: user_group
        description:
      - name: event_name_array
        description: 
      - name: event_count
        description: The count of events
      - name: namespace_count
        description: The count of namespaces
      - name: user_count
        description: The count of users
      - name: created_by
        description: Who created this model?
      - name: update_by
        description: Who updated this model last?
      - name: model_created_date
        description: The date at which the model was created
      - name: model_updated_date
        description: The date at which the model was last updated
