version: 2

models:
    - name: monthly_usage_data_28_days
      description: '{{ doc("monthly_usage_data_28_days") }}'
      columns:
          - name: primary_key
            tests:
              - not_null
              - unique
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: metrics_path
            tests:
              - not_null
    - name: monthly_usage_data_all_time
      description: '{{ doc("monthly_usage_data_all_time") }}'
      columns:
          - name: primary_key
            tests:
              - not_null
              - unique
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: metrics_path
            tests:
              - not_null
    - name: prep_usage_data_7_days_flattened
      description: '{{ doc("prep_usage_data_7_days_flattened") }}'
      columns:
          - name: instance_path_id
            tests:
              - not_null
              - unique
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: metrics_path
            tests:
              - not_null
    - name: prep_usage_data_28_days_flattened
      description: '{{ doc("prep_usage_data_28_days_flattened") }}'
      columns:
          - name: instance_path_id
            tests:
              - not_null
              - unique
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: metrics_path
            tests:
              - not_null
    - name: prep_usage_data_all_time_flattened
      description: '{{ doc("prep_usage_data_all_time_flattened") }}'
      columns:
          - name: instance_path_id
            tests:
              - not_null
              - unique
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: metrics_path
            tests:
              - not_null
