---
version: '2.1'

services:
    master:
        build: .
        environment:
            - CARTE_PORT=8181
            - CARTE_IS_MASTER=Y
            - CARTE_INCLUDE_MASTERS=N
        ports:
            - "8181:8181"
    slave:
        build: .
        environment:
            - CARTE_PORT=8182
            - CARTE_IS_MASTER=N
            - CARTE_MASTER_PORT=8181
            - CARTE_INCLUDE_MASTERS=Y
            - CARTE_MASTER_HOSTNAME=master
        healthcheck:
            test: "carte-healthcheck"
            interval: 30s
            retries: 3
        restart: always
        ports:
            - "8182"
        links:
            - master
