version: 2

sources:
  - name: maxmind
    database: '{{ target.database }}'
    schema: boneyard
    loader: sheetload
    loaded_at_field: _UPDATED_AT

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 36, period: hour}
      error_after: {count: 60, period: hour}

    tables:
      - name: countries
      - name: ranges