version: "1.0"

# Databases
databases:
    - analytics:
        shared: no

    - raw:
        shared: no

    - testing_db:
        shared: no

    - snowflake:
        shared: yes


# Roles
roles:
    ## Admin Roles
    - accountadmin:
        warehouses:
            - loading
        member_of:
            - sysadmin

    - securityadmin:
        warehouses:
            - loading
        member_of:
            - sysadmin

    - sysadmin:
        warehouses:
            - loading
        privileges:
            databases:
                read:
                    - raw
                    - analytics
                write:
                    - raw
                    - analytics
            schemas:
                read:
                    - raw.*
                    - analytics.*
                write:
                    - raw.*
                    - analytics.*
            tables:
                read:
                    - raw.*.*
                    - analytics.*.*
                write:
                    - raw.*.*
                    - analytics.*.*

    ## Regular Roles
    - engineer:
        member_of:
            - sysadmin
        warehouses:
            - loading
        privileges:
            databases:
                read:
                    - raw
                    - analytics
                write:
                    - raw
                    - analytics
            schemas:
                read:
                    - raw.*
                    - analytics.*
                write:
                    - raw.*
                    - analytics.*
            tables:
                read:
                    - raw.*.*
                    - analytics.*.*
                write:
                    - raw.*.*
                    - analytics.*.*

    - loader:
        warehouses:
            - loading
        owns:
            schemas:
                - raw.*
                - testing_db.*
            tables:
                - raw.*.*
                - testing_db.*.*
        privileges:
            databases:
                read:
                    - raw
                    - testing_db
                write:
                    - raw
                    - testing_db
            schemas:
                read:
                    - raw.*
                    - testing_db.*
                write:
                    - raw.*
                    - testing_db.*
            tables:
                read:
                    - raw.*.*
                    - testing_db.*.*
                write:
                    - raw.*.*
                    - testing_db.*.*

    - reporter:
        warehouses:
            - reporting
        privileges:
            databases:
                read:
                    - analytics
                    - snowflake
            schemas:
                read:
                    - analytics.*
                    - snowflake.account_usage

            tables:
                read:
                    - analytics.*.*
                    - snowflake.account_usage.*

    - transformer:
        warehouses:
            - transforming
        owns:
            schemas:
                - analytics.*
            tables:
                - analytics.*.*
        privileges:
            databases:
                read:
                    - raw
                    - analytics
                write:
                    - analytics
            schemas:
                read:
                    - raw.*
                write:
                    - analytics.*
            tables:
                read:
                    - raw.*.*
                write:
                    - analytics.*.*

    # User Roles
    - acarella:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.acarella_scratch

    - amrvaljevich:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.amrvaljevich_scratch
                - analytics.amrvaljevich_scratch_meta

    - crichards:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.crichards_scratch
                - analytics.crichards_scratch_meta

    - dtang:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.dtang_scratch

    - eburke:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.emilie_scratch
                - analytics.emilie_scratch_meta

    - eeastwood:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.eeastwood_scratch
        privileges:
            databases:
                read:
                    - raw
            schemas:
                read:
                    - raw.gitter
                write:
                    - raw.gitter
            tables:
                read:
                    - raw.gitter.*
                write:
                    - raw.gitter.*

    - gitlab-ci:
        warehouses:
            - reporting

    - looker:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.looker_scratch

    - iroussos:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.iroussos_scratch

    - jsalazar:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.jsalazar_scratch
    
    - jurbanc:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.jurbanc_scratch

    - ssichak:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.ssichak_scratch

    - target_snowflake:
        warehouses:
            - reporting
        owns:
            schemas:
                - testing_db.target_snowflake

    - tlapiana:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.tlapiana_scratch

    - tmurphy:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.tmurphy_scratch
                - analytics.tmurphy_scratch_meta

    - tszuromi:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.tszuromi_scratch
        privileges:
            databases:
                read:
                    - raw
            schemas:
                read:
                    - raw.gcloud_postgres_stitch
                    - raw.version_db
            tables:
                read:
                    - raw.gcloud_postgres_stitch.version_usage_data
                    - raw.gcloud_postgres_stitch.version_version_checks
                    - raw.version_db.*

    - wwright:
        warehouses:
            - reporting
        owns:
            schemas:
                - analytics.wwright_scratch

# Users
users:
    - acarella:
        can_login: yes
        member_of:
            - securityadmin
            - sysadmin
            - acarella

    - amrvaljevich:
        can_login: yes
        member_of:
            - sysadmin
            - transformer
            - amrvaljevich        

    - crichards:
        can_login: yes
        member_of:
            - sysadmin
            - transformer
            - crichards 

    - dtang:
        can_login: yes
        member_of:
            - reporter
            - dtang

    - eburke:
        can_login: yes
        member_of:
            - sysadmin
            - transformer
            - eburke
           
    - eeastwood:
        can_login: yes
        member_of:
            - reporter
            - eeastwood

    - gitlab-ci:
        can_login: yes
        member_of:
            - loader
            - reporter
            - sysadmin
            - transformer
            - gitlab-ci

    - looker:
        can_login: yes
        member_of:
            - reporter
            - looker

    - iroussos:
        can_login: yes
        member_of:
            - engineer
            - loader
            - transformer
            - sysadmin
            - iroussos
    
    - jsalazar:
        can_login: yes
        member_of:
            - securityadmin
            - sysadmin
            - jsalazar

    - jurbanc:
        can_login: yes
        member_of:
            - securityadmin
            - sysadmin
            - jurbanc

    - ssichak:
        can_login: yes
        member_of:
            - securityadmin
            - sysadmin
            - ssichak

    - target_snowflake:
        can_login: yes
        member_of:
            - loader
            - target_snowflake

    - tlapiana:
        can_login: yes
        member_of:
            - engineer
            - loader
            - transformer
            - sysadmin
            - tlapiana

    - tmurphy:
        can_login: yes
        member_of:
            - accountadmin
            - engineer
            - sysadmin
            - transformer
            - tmurphy

    - tszuromi:
        can_login: yes
        member_of:
            - reporter
            - tszuromi

    - wwright:
        can_login: yes
        member_of:
            - engineer
            - transformer
            - wwright

# Warehouses
warehouses:
    - loading:
        size: x-small

    - reporting:
        size: x-small

    - transforming:
        size: x-large
        