version: 2
models:
- name: driveload_clari_export_forecast_net_iacv_source
  description: Clari export forcast data primariliy for use by the finance team.
  columns:
    - name: user
      tests:
      - not_null
- name: driveload_email_domain_classification_source
  description: SSOT for email domain classification for personal domains.
  columns:
    - name: domain
      tests:
      - not_null
    - name: classification
      tests:
      - not_null
- name: driveload_ssa_coverage_fitted_curves_source
  description: E
  columns:
    - name: key_agg_day
      tests:
      - not_null
- name: driveload_ssa_quarterly_aggregated_metrics_for_coverage_source
  description: E
  columns:
    - name: agg_key_value
      tests:
      - not_null
