config:
    send_anonymous_usage_stats: False
    use_colors: True

gitlab:
  outputs:
    prod:
      type: postgres
      threads: 2
      host: "{{ env_var('PG_ADDRESS') }}"
      port: "{{ env_var('PG_PORT') }}"
      user: "{{ env_var('PG_USERNAME') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      dbname: "{{ env_var('PG_DATABASE') }}"
      schema: "{{ env_var('PG_PROD_SCHEMA') }}"
    dev:
      type: postgres
      threads: 2
      host: "{{ env_var('PG_ADDRESS') }}"
      port: "{{ env_var('PG_PORT') }}"
      user: "{{ env_var('PG_USERNAME') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      dbname: "{{ env_var('PG_DATABASE') }}"
      schema: "{{ env_var('PG_DEV_SCHEMA') }}"
    local:
      type: postgres
      threads: 2
      host: localhost
      port: "{{ env_var('PG_PORT') }}"
      user: "{{ env_var('PG_USERNAME') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      dbname: "{{ env_var('PG_DATABASE') }}"
      schema: "{{ env_var('PG_DEV_SCHEMA') }}"
    version:
      type: postgres
      threads: 2
      host: localhost
      port: "{{ env_var('PG_PORT') }}"
      user: "{{ env_var('PG_USERNAME') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      dbname: "{{ env_var('PG_DATABASE') }}"
      schema: version
  target: dev