cco_dashboard:
    constraints:
        not_null:
            - primary_key
        unique:
            - primary_key

historical_regional_quota_xf:
    constraints:
        not_null:
            - region_quota_id
        unique:
            - region_quota_id

historical_sales_quota_xf:
    constraints:
        not_null:
            - sales_quota_id
        unique:
            - sales_quota_id
