apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
data:
  proxy-connect-timeout: {{ .Values.proxyConnectTimeout | quote }}
  proxy-read-timeout: {{ .Values.proxyReadTimeout | quote }}
  proxy-send-imeout: {{ .Values.proxySendTimeout | quote }}
  proxy-body-size: {{ .Values.proxyBodySize | quote }}
  hsts-include-subdomains: {{ .Values.hstsIncludeSubdomains | quote }}
  server-name-hash-bucket-size: {{ .Values.serverNameHashBucketSize | quote }}
  enable-vts-status: "true"
