version: 2

models:
    - name: pte_scores_source
      description: '{{ doc("pte_scores_source") }}'
    - name: ptc_scores_source
      description: '{{ doc("ptc_scores_source") }}'
    - name: ptpt_scores_source
      description: '{{ doc("ptpt_scores_source") }}'
    - name: pte_scores
      description: '{{ doc("pte_scores") }}'
    - name: ptc_scores
      description: '{{ doc("ptc_scores") }}'
    - name: ptpt_scores
      description: '{{ doc("ptpt_scores") }}'

