version: 2
models:
- name: employee_directory_analysis
  description: Gives the current state of the employees at GitLab at any point of time. This is the model to use for headcount, team size, or any people-related analysis for employees. This has current and past employees, as well as their department, division, and cost center.
- name: employee_directory
  description: INCLUDES SENSITIVE INFORMATION. The master collection of all info about GitLab employees for all time.
  columns:
  - name: employee_id
    tests:
    - not_null
    - unique
  - name: employee_number
    tests:
    - not_null
    - unique
  - name: first_name
    tests:
    - not_null
  - name: last_name
    tests:
    - not_null
  - name: job_title
  - name: supervisor
  - name: work_email
  - name: hire_date
#    tests:
#     - not_null
  - name: termination_date
  - name: department
  - name: division
  - name: cost_center
  - name: location_factor
