request_stats:
  import_db: GITLAB_PROFILER_DB
  import_query: >
    SELECT id, url, auth_type, html_url, sql_url, gitlab_version, 
           status_code, view_time_ms, sql_time_ms, total_ms, created_at,
           started_at, ended_at
    FROM request_stats
    WHERE created_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'gitlab_profiler'
  export_table: 'request_stats'
  export_table_schema:
    id: integer
    url: text
    auth_type: text
    html_url: text
    sql_url: text
    gitlab_version: text
    status_code: integer
    view_time_ms: double precision
    sql_time_ms: double precision
    total_ms: double precision
    created_at: timestamp without time zone
    started_at: timestamp without time zone
    ended_at: timestamp without time zone
  export_table_primary_key: id
