version: 2

models:
  - name: zi_comp_with_linkages_global
    description: International table, data ingested from Zoominfo inbound share.
    columns:      
      - name: zi_c_id
      - name: zi_c_hq_id
      - name: zi_c_is_hq
      - name: zi_es_ecid
      - name: zi_es_location_id
      - name: zi_c_tier_grade
      - name: zi_c_name
      - name: zi_c_name_display
      - name: zi_c_legal_entity_type
      - name: zi_c_url
      - name: zi_c_street
      - name: zi_c_street_2
      - name: zi_c_city
      - name: zi_c_state
      - name: zi_c_zip
      - name: zi_c_country
      - name: zi_c_cbsa_name
      - name: zi_c_county
      - name: zi_c_latitude
      - name: zi_c_longitude
      - name: zi_c_verified_address
      - name: zi_c_employee_range
      - name: zi_c_employees
      - name: zi_c_revenue_range
      - name: zi_c_revenue
      - name: zi_c_phone
      - name: zi_c_fax
      - name: zi_c_industry_primary
      - name: zi_c_sub_industry_primary
      - name: zi_c_industries
      - name: zi_c_sub_industries
      - name: zi_es_industry
      - name: zi_es_industries_top3
      - name: zi_c_naics2
      - name: zi_c_naics4
      - name: zi_c_naics6
      - name: zi_c_naics_top3
      - name: zi_c_sic2
      - name: zi_c_sic3
      - name: zi_c_sic4
      - name: zi_c_sic_top3
      - name: zi_c_estimated_age
      - name: zi_c_year_founded
      - name: zi_c_is_b2b
      - name: zi_c_is_b2c
      - name: zi_es_hq_ecid
      - name: zi_es_hq_location_id
      - name: zi_c_hq_name
      - name: zi_c_hq_url
      - name: zi_c_hq_street
      - name: zi_c_hq_street_2
      - name: zi_c_hq_city
      - name: zi_c_hq_state
      - name: zi_c_hq_zip
      - name: zi_c_hq_country
      - name: zi_c_hq_cbsa_name
      - name: zi_c_hq_county
      - name: zi_c_hq_latitude
      - name: zi_c_hq_longitude
      - name: zi_c_hq_verified_address
      - name: zi_c_hq_employee_range
      - name: zi_c_hq_employees
      - name: zi_c_hq_revenue_range
      - name: zi_c_hq_revenue
      - name: zi_c_hq_phone
      - name: zi_c_hq_fax
      - name: zi_c_linkedin_url
      - name: zi_c_facebook_url
      - name: zi_c_twitter_url
      - name: zi_c_yelp_url
      - name: zi_c_alexa_rank
      - name: zi_c_keywords
      - name: zi_c_top_keywords
      - name: zi_c_num_keywords
      - name: zi_c_employee_growth_1yr
      - name: zi_c_employee_growth_2yr
      - name: zi_es_growth
      - name: zi_es_employee_growth
      - name: zi_es_revenue_growth
      - name: zi_es_percent_employee_growth
      - name: zi_es_percent_revenue_growth
      - name: zi_c_name_confidence_score
      - name: zi_c_url_confidence_score
      - name: zi_c_address_confidence_score
      - name: zi_c_phone_confidence_score
      - name: zi_c_employees_confidence_score
      - name: zi_c_revenue_confidence_score
      - name: zi_es_industry_confidence_score
      - name: zi_c_naics_confidence_score
      - name: zi_c_sic_confidence_score
      - name: zi_es_industries_top3_confidence_scores
      - name: zi_c_naics_top3_confidence_scores
      - name: zi_c_sic_top3_confidence_scores
      - name: zi_c_ids_merged
      - name: zi_c_names_other
      - name: zi_c_url_status
      - name: zi_c_urls_alt
      - name: zi_c_url_last_updated
      - name: zi_c_inactive_flag
      - name: zi_c_ein
      - name: zi_c_is_small_business
      - name: zi_c_is_public
      - name: zi_c_ticker
      - name: zi_c_tickers_alt
      - name: zi_c_has_mobile_app
      - name: zi_c_currency_code
      - name: zi_c_num_locations
      - name: zi_c_hr_contacts
      - name: zi_c_sales_contacts
      - name: zi_c_marketing_contacts
      - name: zi_c_finance_contacts
      - name: zi_c_c_suite_contacts
      - name: zi_c_engineering_contacts
      - name: zi_c_it_contacts
      - name: zi_c_operations_contacts
      - name: zi_c_legal_contacts
      - name: zi_c_medical_contacts
      - name: zi_c_tech_ids
      - name: zi_c_latest_funding_age
      - name: zi_c_num_of_investors
      - name: zi_c_investor_names
      - name: zi_c_funding_strength
      - name: zi_c_funding_type
      - name: zi_c_total_funding_amount
      - name: zi_c_latest_funding_amount
      - name: zi_c_latest_funding_date
      - name: zi_c_num_funding_rounds
      - name: zi_c_is_fortune_100
      - name: zi_c_is_fortune_500
      - name: zi_c_is_s_and_p_500
      - name: zi_c_is_domestic_hq
      - name: zi_c_is_global_parent
      - name: zi_c_is_subsidiary
      - name: zi_c_is_franchisor
      - name: zi_c_is_franchisee
      - name: zi_c_hierarchy_code
      - name: zi_c_hierarchy_level
      - name: zi_c_parent_child_confidence_score
      - name: zi_c_immediate_parent_id
      - name: zi_es_immediate_parent_ecid
      - name: zi_es_immediate_parent_location_id
      - name: zi_c_immediate_parent_name
      - name: zi_c_immediate_parent_url
      - name: zi_c_immediate_parent_street
      - name: zi_c_immediate_parent_street_2
      - name: zi_c_immediate_parent_city
      - name: zi_c_immediate_parent_zip
      - name: zi_c_immediate_parent_state
      - name: zi_c_immediate_parent_country
      - name: zi_c_domestic_parent_id
      - name: zi_es_domestic_parent_ecid
      - name: zi_es_domestic_parent_location_id
      - name: zi_c_domestic_parent_name
      - name: zi_c_domestic_parent_url
      - name: zi_c_domestic_parent_street
      - name: zi_c_domestic_parent_street_2
      - name: zi_c_domestic_parent_city
      - name: zi_c_domestic_parent_zip
      - name: zi_c_domestic_parent_state
      - name: zi_c_domestic_parent_country
      - name: zi_c_global_parent_id
      - name: zi_es_global_parent_ecid
      - name: zi_es_global_parent_location_id
      - name: zi_c_global_parent_name
      - name: zi_c_global_parent_url
      - name: zi_c_global_parent_street
      - name: zi_c_global_parent_street_2
      - name: zi_c_global_parent_city
      - name: zi_c_global_parent_zip
      - name: zi_c_global_parent_state
      - name: zi_c_global_parent_country
      - name: zi_c_franchisor_id
      - name: zi_es_franchisor_ecid
      - name: zi_es_franchisor_location_id
      - name: zi_c_franchisor_name
      - name: zi_c_franchisor_url
      - name: zi_c_franchisor_street
      - name: zi_c_franchisor_street_2
      - name: zi_c_franchisor_city
      - name: zi_c_franchisor_zip
      - name: zi_c_franchisor_state
      - name: zi_c_franchisor_country
      - name: zi_c_last_updated_date
      - name: zi_c_release_date

  - name: zi_reference_techs
    description: Technograph table, data ingested from Zoominfo inbound share.
    columns: 
      - name: zi_c_tech_id
      - name: zi_c_tech_name
      - name: zi_c_category
      - name: zi_c_category_parent
      - name: zi_c_vendor
      - name: zi_c_tech_domain
      - name: zi_c_description
  
  - name: user_enrichment
    description: User company matched table which appends company information to the user list Gitlab sends to zoominfo. Data ingested from Zoominfo inbound share.
    columns:
      - name: zi_c_id
      - name: zi_c_hq_id
      - name: zi_c_is_hq
      - name: zi_es_ecid
      - name: zi_es_location_id
      - name: zi_c_tier_grade
      - name: zi_c_name
      - name: zi_c_name_display
      - name: zi_c_legal_entity_type
      - name: zi_c_url
      - name: zi_c_street
      - name: zi_c_street_2
      - name: zi_c_city
      - name: zi_c_state
      - name: zi_c_zip
      - name: zi_c_country
      - name: zi_c_cbsa_name
      - name: zi_c_county
      - name: zi_c_latitude
      - name: zi_c_longitude
      - name: zi_c_verified_address
      - name: zi_c_employee_range
      - name: zi_c_employees
      - name: zi_c_revenue_range
      - name: zi_c_revenue
      - name: zi_c_phone
      - name: zi_c_fax
      - name: zi_c_industry_primary
      - name: zi_c_sub_industry_primary
      - name: zi_c_industries
      - name: zi_c_sub_industries
      - name: zi_es_industry
      - name: zi_es_industries_top3
      - name: zi_c_naics2
      - name: zi_c_naics4
      - name: zi_c_naics6
      - name: zi_c_naics_top3
      - name: zi_c_sic2
      - name: zi_c_sic3
      - name: zi_c_sic4
      - name: zi_c_sic_top3
      - name: zi_c_estimated_age
      - name: zi_c_year_founded
      - name: zi_c_is_b2b
      - name: zi_c_is_b2c
      - name: zi_es_hq_ecid
      - name: zi_es_hq_location_id
      - name: zi_c_hq_name
      - name: zi_c_hq_url
      - name: zi_c_hq_street
      - name: zi_c_hq_street_2
      - name: zi_c_hq_city
      - name: zi_c_hq_state
      - name: zi_c_hq_zip
      - name: zi_c_hq_country
      - name: zi_c_hq_cbsa_name
      - name: zi_c_hq_county
      - name: zi_c_hq_latitude
      - name: zi_c_hq_longitude
      - name: zi_c_hq_verified_address
      - name: zi_c_hq_employee_range
      - name: zi_c_hq_employees
      - name: zi_c_hq_revenue_range
      - name: zi_c_hq_revenue
      - name: zi_c_hq_phone
      - name: zi_c_hq_fax
      - name: zi_c_linkedin_url
      - name: zi_c_facebook_url
      - name: zi_c_twitter_url
      - name: zi_c_yelp_url
      - name: zi_c_alexa_rank
      - name: zi_c_keywords
      - name: zi_c_top_keywords
      - name: zi_c_num_keywords
      - name: zi_c_employee_growth_1yr
      - name: zi_c_employee_growth_2yr
      - name: zi_es_growth
      - name: zi_es_employee_growth
      - name: zi_es_revenue_growth
      - name: zi_es_percent_employee_growth
      - name: zi_es_percent_revenue_growth
      - name: zi_c_name_confidence_score
      - name: zi_c_url_confidence_score
      - name: zi_c_address_confidence_score
      - name: zi_c_phone_confidence_score
      - name: zi_c_employees_confidence_score
      - name: zi_c_revenue_confidence_score
      - name: zi_es_industry_confidence_score
      - name: zi_c_naics_confidence_score
      - name: zi_c_sic_confidence_score
      - name: zi_es_industries_top3_confidence_scores
      - name: zi_c_naics_top3_confidence_scores
      - name: zi_c_sic_top3_confidence_scores
      - name: zi_c_ids_merged
      - name: zi_c_names_other
      - name: zi_c_url_status
      - name: zi_c_urls_alt
      - name: zi_c_url_last_updated
      - name: zi_c_inactive_flag
      - name: zi_c_ein
      - name: zi_c_is_small_business
      - name: zi_c_is_public
      - name: zi_c_ticker
      - name: zi_c_tickers_alt
      - name: zi_c_has_mobile_app
      - name: zi_c_currency_code
      - name: zi_c_num_locations
      - name: zi_c_hr_contacts
      - name: zi_c_sales_contacts
      - name: zi_c_marketing_contacts
      - name: zi_c_finance_contacts
      - name: zi_c_c_suite_contacts
      - name: zi_c_engineering_contacts
      - name: zi_c_it_contacts
      - name: zi_c_operations_contacts
      - name: zi_c_legal_contacts
      - name: zi_c_medical_contacts
      - name: zi_c_tech_ids
      - name: zi_c_latest_funding_age
      - name: zi_c_num_of_investors
      - name: zi_c_investor_names
      - name: zi_c_funding_strength
      - name: zi_c_funding_type
      - name: zi_c_total_funding_amount
      - name: zi_c_latest_funding_amount
      - name: zi_c_latest_funding_date
      - name: zi_c_num_funding_rounds
      - name: zi_c_is_domestic_hq
      - name: zi_c_is_global_parent
      - name: zi_c_is_subsidiary
      - name: zi_c_is_franchisor
      - name: zi_c_is_franchisee
      - name: zi_c_hierarchy_code
      - name: zi_c_hierarchy_level
      - name: zi_c_immediate_parent_id
      - name: zi_es_immediate_parent_ecid
      - name: zi_es_immediate_parent_location_id
      - name: zi_c_immediate_parent_name
      - name: zi_c_immediate_parent_url
      - name: zi_c_immediate_parent_street
      - name: zi_c_immediate_parent_street_2
      - name: zi_c_immediate_parent_city
      - name: zi_c_immediate_parent_zip
      - name: zi_c_immediate_parent_state
      - name: zi_c_immediate_parent_country
      - name: zi_c_domestic_parent_id
      - name: zi_es_domestic_parent_ecid
      - name: zi_es_domestic_parent_location_id
      - name: zi_c_domestic_parent_name
      - name: zi_c_domestic_parent_url
      - name: zi_c_domestic_parent_street
      - name: zi_c_domestic_parent_street_2
      - name: zi_c_domestic_parent_city
      - name: zi_c_domestic_parent_zip
      - name: zi_c_domestic_parent_state
      - name: zi_c_domestic_parent_country
      - name: zi_c_global_parent_id
      - name: zi_es_global_parent_ecid
      - name: zi_es_global_parent_location_id
      - name: zi_c_global_parent_name
      - name: zi_c_global_parent_url
      - name: zi_c_global_parent_street
      - name: zi_c_global_parent_street_2
      - name: zi_c_global_parent_city
      - name: zi_c_global_parent_zip
      - name: zi_c_global_parent_state
      - name: zi_c_global_parent_country
      - name: zi_c_franchisor_id
      - name: zi_es_franchisor_ecid
      - name: zi_es_franchisor_location_id
      - name: zi_c_franchisor_name
      - name: zi_c_franchisor_url
      - name: zi_c_franchisor_street
      - name: zi_c_franchisor_street_2
      - name: zi_c_franchisor_city
      - name: zi_c_franchisor_zip
      - name: zi_c_franchisor_state
      - name: zi_c_franchisor_country
      - name: zi_c_last_updated_date
      - name: zi_c_release_date
