version: 2

sources:
  - name: zoominfo
    database: "ZOOMINFO_INBOUND"
    schema: gitlab
    loader: Snowflake Data Exchange
    
    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: global
        identifier: zi_comp_with_linkages_20211001_global         
        description: International table, data ingested from Zoominfo inbound share.
        loaded_at_field: uploaded_at

      - name: techs
        identifier: reference_techs         
        description: Technograph table,  data ingested from Zoominfo inbound share.
        loaded_at_field: uploaded_at
           
      - name: user
        identifier: udb_sample_09012021         
        description: User company matched table which appends company information to the user list Gitlab sends to zoominfo. Data ingested from Zoominfo inbound share.
        loaded_at_field: uploaded_at

