version: 2

sources:
  - name: zuora_data_query
    tags: ["tdf","zuora"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: zuora_data_query
    loader: Stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: users
