Required:
  - PG_ADDRESS
  - PG_PORT
  - PG_DATABASE
  - PG_USERNAME
  - PG_PASSWORD

  - SNOWFLAKE_LOAD_ACCOUNT
  - SNOWFLAKE_LOAD_USER
  - SNOWFLAKE_LOAD_PASSWORD
  - SNOWFLAKE_LOAD_ROLE
  - SNOWFLAKE_LOADING_WAREHOUSE
  
  - VERSION_DB_USER
  - VERSION_DB_HOST
  - VERSION_DB_NAME

  - CUSTOMER_DB_USER
  - CUSTOMER_DB_HOST
  - CUSTOMER_DB_NAME

  - LICENSE_DB_USER
  - LICENSE_DB_HOST
  - LICENSE_DB_NAME

  - CI_STATS_DB_USER
  - CI_STATS_DB_HOST
  - CI_STATS_DB_NAME

  - GITLAB_PROFILER_DB_USER
  - GITLAB_PROFILER_DB_PASS
  - GITLAB_PROFILER_DB_HOST
  - GITLAB_PROFILER_DB_NAME