version: 2

models:
    - name: bamboohr_directory
      description: Base model for BambooHR Active Directory. This only shows currently active employees.
      columns:
          - name: employee_id
            tests:
                - not_null
                - unique
          - name: full_name
            tests:
                - not_null
          - name: first_name
            tests:
                - not_null
          - name: last_name
            tests:
                - not_null
          - name: preferred_name
          - name: binary_gender
          - name: job_title