version: 2

sources:
  - name: bamboohr
    database: raw
    schema: bamboohr
    loader: Airflow
    loaded_at_field: uploaded_at

    freshness:
      warn_after: {count: 24, period: hour}

    tables:
      - name: compensation
      - name: custom_bonus
        identifier: custombonus
      - name: directory
      - name: employment_status
        identifier: employmentstatus
      - name: job_info
        identifier: jobinfo
