version: 2

models:
  - name: fct_invoice
    description: '{{ doc("fct_invoice") }}'
    columns:
      - name: dim_invoice_id
        description: The unique identifier of an invoice
        tests:
          - not_null
          - unique
        tags: ["tdf", "common", "invoice"]