connection_info:
  account: BIZIBLE_SNOWFLAKE_ACCOUNT
  database: BIZIBLE_SNOWFLAKE_DATABASE
  pass: BIZIBLE_SNOWFLAKE_PASSWORD
  user: BIZIBLE_SNOWFLAKE_USER
  role: BIZIBLE_SNOWFLAKE_ROLE
  warehouse: BIZIBLE_SNOWFLAKE_WAREHOUSE
tables:
  - biz_accounts
  - biz_account_to_emails
  - biz_activities
  - biz_ads
  - biz_advertisers
  - biz_ad_accounts
  - biz_ad_campaigns
  - biz_ad_groups
  - biz_ad_providers
  - biz_campaign_members
  - biz_channels
  - biz_contacts
  - biz_conversion_rates
  - biz_costs
  - biz_creatives
  - biz_crm_tasks
  - biz_currencies
  - biz_email_to_visitor_ids
  - biz_facts
  - biz_lead_stage_transitions
  - biz_segments
  - biz_sites
  - biz_site_links
  - biz_urls
  - biz_customer_ab_tests
  - biz_opportunities
  - biz_sessions
  - biz_user_touchpoints
  - biz_attribution_touchpoints
  - biz_form_submits
  - biz_keywords
  - biz_leads
  - biz_opp_stage_transitions
  - biz_touchpoints
  - biz_crm_events
  - biz_page_views
  - biz_stage_definitions
  - biz_placements
  - biz_web_host_mappings