version: 2

models:
  - name: map_geo_region
    description: Mapping table for cleaning up region names built off ATAM_Region__C in SFDC
  - name: map_geo_sub_region
    description: Mapping table for cleaning up sub region names built off ATAM_Sub_Region__C in SFDC