version: 2

models:
  - name: arr_data_mart
    description: '{{ doc("arr_data_mart") }}'
    columns:
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: mrr_id
        tests:
            - not_null
            - unique
  - name: arr_data_mart_incr
    description: '{{ doc("arr_data_mart_incr") }}'
    columns:
      - name: primary_key
        tests:
          - not_null
  - name: usage_ping_mart
    description: '{{ doc("usage_ping_mart") }}'
    columns:
      - name: usage_ping_id
        tests:
          - not_null
          - unique
      - name: uuid
        tests:
          - not_null
      - name: date_id
        tests:
          - not_null        