version: 2

models:
    -   name: gitlab_create_activation_events
        description: This is the base table for snowplow events captured by Fishtown's infrastructure. It unpacks all of the JSON, including unstructured events.
        columns:
            -   name: uploaded_at
                tests:
                    - not_null
