version: 2

models:
    - name: saas_usage_ping_gitlab_dotcom
      description: Source table for the RAW saas_usage_ping.gitlab_dotcom table
      columns:
        - name: saas_usage_ping_gitlab_dotcom_id
          tests:
            - not_null
            - unique
    - name: saas_usage_ping_gitlab_dotcom_namespace
      description: Source table for the RAW saas_usage_ping.gitlab_dotcom_namespaces table
      columns:
        - name: saas_usage_ping_gitlab_dotcom_namespace_id
          tests:
            - not_null
            - unique
