version: 2

models:
    - name: version_usage_data_month
      description: usage ping data values aggregated by month for each UUID.
      columns:
          - name: created_at
            tests:
                - not_null
          - name: unique_key
            tests:
                - not_null
          - name: uuid
            tests:
                - not_null    
    - name: version_user_activity_by_stage_monthly_unpacked
      description: '{{ doc("version_user_activity_by_stage_monthly_unpacked") }}'
      columns:
          - name: main_edition
            description: Comes from [this section of the code](https://gitlab.com/gitlab-org/gitlab/blob/2dae25c3b780205f072833cd290e481dae436f3b/lib/gitlab/usage_data.rb#L154)
            tests:
                - accepted_values:
                    values: ['EE', 'CE']
          - name: uuid
            tests:
                - not_null
          - name: zuora_subscription_id
            description: The Zuora subscription associated with the license sending the usage ping.
